import { uid } from '../core/types.js';
import { touchProject, createVoice, beatOf, carrierOf } from '../core/project.js';
const fmt = (n, d = 2) => Number.isFinite(n) ? Number(n).toFixed(d) : '—';
const curves = ['hold', 'linear', 'smooth', 'exponential', 'logarithmic', 'bezier'];
const waveforms = ['sine', 'sine2', 'triangle', 'square', 'smooth-square', 'saw', 'reverse-saw', 'pulse', 'bandlimited-square', 'bandlimited-saw', 'custom-harmonic', 'imported-cycle'];
const generators = ['binaural', 'monaural', 'isochronic', 'am', 'stereo', 'noise-modulated', 'sham'];
const laneParams = ['beatHz', 'carrierHz', 'leftHz', 'rightHz', 'amplitude', 'pan', 'duty'];
function num(x, f = 0) { const n = Number(x); return Number.isFinite(n) ? n : f; }
function NumberInput({ label, value, onChange, min, max, step = .01, suffix }) { return React.createElement("label", { className: "studio-field" },
    React.createElement("span", null, label),
    React.createElement("div", { className: "input-suffix" },
        React.createElement("input", { type: "number", value: Number.isFinite(value) ? value : '', min: min, max: max, step: step, onChange: e => onChange(num(e.target.value, value)) }),
        suffix && React.createElement("i", null, suffix))); }
function TrackRows({ project, selection, setSelection, setProject }) {
    const toggle = (kind, id, key) => setProject((p) => touchProject({ ...p, [kind]: p[kind] instanceof Array ? p[kind].map((x) => x.id === id ? { ...x, [key]: !x[key] } : x) : p[kind] }));
    return React.createElement("div", { className: "studio-track-list", role: "listbox", "aria-label": "Tracks" },
        React.createElement("div", { className: "track-group-label" }, "STIMULUS"),
        project.voices.map((v) => React.createElement("div", { className: 'studio-track-row ' + (selection.kind === 'voice' && selection.id === v.id ? 'selected' : ''), key: v.id, onClick: () => setSelection({ kind: 'voice', id: v.id }) },
            React.createElement("button", { className: "track-main" },
                React.createElement("b", null, v.name),
                React.createElement("small", null,
                    v.type,
                    " \u00B7 \u0394 ",
                    fmt(beatOf(v)),
                    " Hz")),
            React.createElement("button", { "aria-label": `Mute ${v.name}`, className: v.mute ? 'tiny active' : '', onClick: (e) => { e.stopPropagation(); toggle('voices', v.id, 'mute'); } }, "M"),
            React.createElement("button", { "aria-label": `Solo ${v.name}`, className: v.solo ? 'tiny active' : '', onClick: (e) => { e.stopPropagation(); toggle('voices', v.id, 'solo'); } }, "S"))),
        React.createElement("div", { className: "track-group-label" }, "NOISE / BACKGROUND"),
        project.noiseTracks.map((n) => React.createElement("div", { className: 'studio-track-row ' + (selection.kind === 'noise' && selection.id === n.id ? 'selected' : ''), key: n.id, onClick: () => setSelection({ kind: 'noise', id: n.id }) },
            React.createElement("button", { className: "track-main" },
                React.createElement("b", null, n.name),
                React.createElement("small", null,
                    n.kind,
                    " noise")),
            React.createElement("button", { className: n.mute ? 'tiny active' : '', onClick: (e) => { e.stopPropagation(); toggle('noiseTracks', n.id, 'mute'); } }, "M"),
            React.createElement("button", { className: n.solo ? 'tiny active' : '', onClick: (e) => { e.stopPropagation(); toggle('noiseTracks', n.id, 'solo'); } }, "S"))),
        project.audioTracks.map((a) => React.createElement("div", { className: 'studio-track-row ' + (selection.kind === 'audio' && selection.id === a.id ? 'selected' : ''), key: a.id, onClick: () => setSelection({ kind: 'audio', id: a.id }) },
            React.createElement("button", { className: "track-main" },
                React.createElement("b", null, a.name),
                React.createElement("small", null,
                    "audio \u00B7 ",
                    fmt(a.duration, 1),
                    " s")),
            React.createElement("button", { className: a.mute ? 'tiny active' : '', onClick: (e) => { e.stopPropagation(); toggle('audioTracks', a.id, 'mute'); } }, "M"),
            React.createElement("button", { className: a.solo ? 'tiny active' : '', onClick: (e) => { e.stopPropagation(); toggle('audioTracks', a.id, 'solo'); } }, "S"))));
}
function Clip({ start, duration, total, label, sub, onChange }) { const drag = React.useRef(null); const down = (e) => { if (e.button !== 0)
    return; drag.current = { x: e.clientX, start }; const move = (m) => { if (!drag.current)
    return; const el = e.currentTarget.parentElement, w = Math.max(1, el.getBoundingClientRect().width), dt = (m.clientX - drag.current.x) / w * total; onChange(Math.max(0, Math.min(total - duration, drag.current.start + dt))); }; const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); drag.current = null; }; addEventListener('pointermove', move); addEventListener('pointerup', up); }; return React.createElement("div", { className: "timeline-clip", onPointerDown: down, style: { left: `${start / total * 100}%`, width: `${Math.max(.5, duration / total * 100)}%` } },
    React.createElement("b", null, label),
    React.createElement("small", null, sub)); }
function AutomationEditor({ voice, setProject, project }) { const [parameter, setParameter] = React.useState('beatHz'); const [clipboard, setClipboard] = React.useState(null); const lane = voice.automation.find((x) => x.parameter === parameter); const fallback = parameter === 'beatHz' ? beatOf(voice) : parameter === 'carrierHz' ? carrierOf(voice) : parameter === 'leftHz' ? voice.leftHz : parameter === 'rightHz' ? voice.rightHz : parameter === 'amplitude' ? voice.amplitude : parameter === 'duty' ? voice.duty : 0; const points = (lane?.points?.length ? lane.points : [{ id: 'virtual-a', time: 0, value: fallback, curve: 'linear' }, { id: 'virtual-b', time: voice.duration, value: fallback, curve: 'linear' }]); const vals = points.map(p => p.value), lo = Math.min(...vals, fallback), hi = Math.max(...vals, fallback), range = Math.max(1e-6, hi - lo), pad = range * .2; const yMin = lo - pad, yMax = hi + pad; const update = (next) => setProject((p) => touchProject({ ...p, voices: p.voices.map(v => v.id === voice.id ? { ...v, automation: [...v.automation.filter(a => a.parameter !== parameter), { parameter, points: next.sort((a, b) => a.time - b.time) }] } : v) })); const add = (e) => { const r = e.currentTarget.getBoundingClientRect(), x = (e.clientX - r.left) / r.width, y = (e.clientY - r.top) / r.height, time = Math.max(0, Math.min(voice.duration, x * voice.duration)), value = yMax - y * (yMax - yMin); update([...(lane?.points || []), { id: uid('point'), time, value, curve: 'linear' }]); }; const drag = (e, p) => { e.stopPropagation(); const svg = e.currentTarget.ownerSVGElement, r = svg.getBoundingClientRect(); const move = (m) => { const x = Math.max(0, Math.min(1, (m.clientX - r.left) / r.width)), y = Math.max(0, Math.min(1, (m.clientY - r.top) / r.height)); update(points.filter(x => !x.id.startsWith('virtual')).map(q => q.id === p.id ? { ...q, time: x * voice.duration, value: yMax - y * (yMax - yMin) } : q)); }; const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); }; addEventListener('pointermove', move); addEventListener('pointerup', up); }; const real = lane?.points || []; const path = points.map((p, i) => `${i ? 'L' : 'M'} ${(p.time / voice.duration) * 800} ${100 - (p.value - yMin) / (yMax - yMin) * 100}`).join(' '); return React.createElement("section", { className: "automation-editor" },
    React.createElement("div", { className: "automation-head" },
        React.createElement("b", null, "Automation"),
        React.createElement("select", { value: parameter, onChange: e => setParameter(e.target.value) }, laneParams.map(x => React.createElement("option", { key: x }, x))),
        React.createElement("button", { onClick: () => setClipboard(lane ? structuredClone(lane) : null), disabled: !lane }, "Copy"),
        React.createElement("button", { onClick: () => clipboard && update(clipboard.points.map(p => ({ ...p, id: uid('point') }))), disabled: !clipboard }, "Paste"),
        React.createElement("button", { onClick: () => update([]), disabled: !lane }, "Clear")),
    React.createElement("svg", { viewBox: "0 0 800 100", preserveAspectRatio: "none", onDoubleClick: add, "aria-label": `${parameter} automation graph` },
        React.createElement("path", { d: path, fill: "none", stroke: "currentColor", strokeWidth: "2" }),
        points.map(p => React.createElement("circle", { key: p.id, cx: (p.time / voice.duration) * 800, cy: 100 - (p.value - yMin) / (yMax - yMin) * 100, r: "6", onPointerDown: (e) => !p.id.startsWith('virtual') && drag(e, p) }))),
    React.createElement("small", null, "Double-click graph to add a point; drag points to edit."),
    real.length > 0 && React.createElement("div", { className: "automation-table" }, real.map((p) => React.createElement("div", { key: p.id },
        React.createElement("input", { "aria-label": "Point time", type: "number", step: ".01", value: p.time, onChange: e => update(real.map(q => q.id === p.id ? { ...q, time: Math.max(0, Math.min(voice.duration, num(e.target.value))) } : q)) }),
        React.createElement("input", { "aria-label": "Point value", type: "number", step: ".01", value: p.value, onChange: e => update(real.map(q => q.id === p.id ? { ...q, value: num(e.target.value) } : q)) }),
        React.createElement("select", { value: p.curve, onChange: e => update(real.map(q => q.id === p.id ? { ...q, curve: e.target.value } : q)) }, curves.map(c => React.createElement("option", { key: c }, c))),
        React.createElement("button", { "aria-label": "Delete automation point", onClick: () => update(real.filter(q => q.id !== p.id)) }, "\u00D7"))))); }
function TrackAutomationControls({ track, patch, parameters }) { const [parameter, setParameter] = React.useState(parameters[0]); const lane = (track.automation || []).find((x) => x.parameter === parameter); const fallback = Number(track[parameter] ?? 0); const setLane = (points) => patch({ automation: [...(track.automation || []).filter((x) => x.parameter !== parameter), { parameter, points }] }); const addRamp = () => setLane([{ id: uid('point'), time: 0, value: fallback, curve: 'linear' }, { id: uid('point'), time: track.duration || 1, value: fallback, curve: 'linear' }]); const addMod = () => patch({ modulation: [...(track.modulation || []), { target: parameter, rateHz: 1, depth: .05, phase: 0, offset: 0 }] }); return React.createElement("div", { className: "track-automation" },
    React.createElement("h4", null, "Automation / modulation"),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Parameter"),
        React.createElement("select", { value: parameter, onChange: e => setParameter(e.target.value) }, parameters.map((x) => React.createElement("option", { key: x }, x)))),
    React.createElement("div", { className: "actions" },
        React.createElement("button", { onClick: addRamp }, lane ? 'Reset ramp' : '+ Ramp'),
        React.createElement("button", { onClick: addMod }, "+ LFO")),
    lane && React.createElement("div", { className: "automation-table" }, lane.points.map((pt) => React.createElement("div", { key: pt.id },
        React.createElement("input", { "aria-label": "Automation time", type: "number", min: "0", max: track.duration, step: ".01", value: pt.time, onChange: e => setLane(lane.points.map((q) => q.id === pt.id ? { ...q, time: num(e.target.value) } : q)) }),
        React.createElement("input", { "aria-label": "Automation value", type: "number", step: ".01", value: pt.value, onChange: e => setLane(lane.points.map((q) => q.id === pt.id ? { ...q, value: num(e.target.value) } : q)) }),
        React.createElement("select", { value: pt.curve, onChange: e => setLane(lane.points.map((q) => q.id === pt.id ? { ...q, curve: e.target.value } : q)) }, curves.map(c => React.createElement("option", { key: c }, c))),
        React.createElement("button", { onClick: () => setLane(lane.points.filter((q) => q.id !== pt.id)) }, "\u00D7")))),
    (track.modulation || []).map((m, i) => React.createElement("div", { className: "link-row", key: `${m.target}-${i}` },
        React.createElement("select", { value: m.target, onChange: e => patch({ modulation: track.modulation.map((q, j) => j === i ? { ...q, target: e.target.value } : q) }) }, parameters.map((x) => React.createElement("option", { key: x }, x))),
        React.createElement("input", { "aria-label": "LFO rate Hz", type: "number", min: "0", step: ".01", value: m.rateHz, onChange: e => patch({ modulation: track.modulation.map((q, j) => j === i ? { ...q, rateHz: num(e.target.value) } : q) }) }),
        React.createElement("input", { "aria-label": "LFO depth", type: "number", step: ".01", value: m.depth, onChange: e => patch({ modulation: track.modulation.map((q, j) => j === i ? { ...q, depth: num(e.target.value) } : q) }) }),
        React.createElement("button", { onClick: () => patch({ modulation: track.modulation.filter((_, j) => j !== i) }) }, "\u00D7")))); }
function VoiceInspector({ project, voice, setProject }) { const patch = (x) => setProject((p) => touchProject({ ...p, voices: p.voices.map(v => v.id === voice.id ? { ...v, ...x } : v) })); const addLink = () => patch({ links: [...voice.links, { id: uid('link'), source: 'time', target: 'beatHz', scale: 1, offset: 0 }] }); return React.createElement("div", { className: "studio-inspector" },
    React.createElement("h3", null, "Voice"),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Name"),
        React.createElement("input", { value: voice.name, onChange: e => patch({ name: e.target.value }) })),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Generator"),
        React.createElement("select", { value: voice.type, onChange: e => patch({ type: e.target.value }) }, generators.map(x => React.createElement("option", { key: x }, x)))),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Waveform"),
        React.createElement("select", { value: voice.waveform, onChange: e => patch({ waveform: e.target.value }) }, waveforms.map(x => React.createElement("option", { key: x }, x)))),
    voice.waveform === 'custom-harmonic' && React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Harmonics (comma amplitudes)"),
        React.createElement("input", { value: (voice.harmonics || [1, .5, .25]).join(','), onChange: e => patch({ harmonics: e.target.value.split(',').map(Number).filter(Number.isFinite).slice(0, 64) }) })),
    voice.waveform === 'imported-cycle' && React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Cycle source"),
        React.createElement("select", { value: voice.cycleAssetId || '', onChange: e => patch({ cycleAssetId: e.target.value || undefined }) },
            React.createElement("option", { value: "" }, "Choose imported audio\u2026"),
            project.assets.map((a) => React.createElement("option", { key: a.id, value: a.id }, a.name))),
        React.createElement("small", null, "The selected audio asset is treated as one periodic waveform cycle; use a clean single-cycle source for predictable spectra.")),
    React.createElement("h4", null, "Waveform timeline"),
    (voice.waveformAutomation || []).map((wp) => React.createElement("div", { className: "link-row", key: wp.id },
        React.createElement("input", { "aria-label": "Waveform change time", type: "number", min: "0", max: voice.duration, step: ".01", value: wp.time, onChange: e => patch({ waveformAutomation: (voice.waveformAutomation || []).map((x) => x.id === wp.id ? { ...x, time: num(e.target.value) } : x) }) }),
        React.createElement("select", { value: wp.waveform, onChange: e => patch({ waveformAutomation: (voice.waveformAutomation || []).map((x) => x.id === wp.id ? { ...x, waveform: e.target.value } : x) }) }, waveforms.map(x => React.createElement("option", { key: x }, x))),
        React.createElement("button", { onClick: () => patch({ waveformAutomation: (voice.waveformAutomation || []).filter((x) => x.id !== wp.id) }) }, "\u00D7"))),
    React.createElement("button", { onClick: () => patch({ waveformAutomation: [...(voice.waveformAutomation || []), { id: uid('wavepoint'), time: voice.duration / 2, waveform: 'triangle' }] }) }, "+ Waveform change"),
    React.createElement(NumberInput, { label: "Left ear", value: voice.leftHz, suffix: "Hz", step: ".001", min: .001, onChange: (x) => patch({ leftHz: x }) }),
    React.createElement(NumberInput, { label: "Right ear", value: voice.rightHz, suffix: "Hz", step: ".001", min: .001, onChange: (x) => patch({ rightHz: x }) }),
    React.createElement(NumberInput, { label: "Amplitude", value: voice.amplitude, step: ".005", min: 0, max: 2, onChange: (x) => patch({ amplitude: x }) }),
    React.createElement(NumberInput, { label: "Left level", value: voice.leftLevel, step: ".01", min: 0, max: 2, onChange: (x) => patch({ leftLevel: x }) }),
    React.createElement(NumberInput, { label: "Right level", value: voice.rightLevel, step: ".01", min: 0, max: 2, onChange: (x) => patch({ rightLevel: x }) }),
    React.createElement(NumberInput, { label: "Start", value: voice.start, suffix: "s", min: 0, onChange: (x) => patch({ start: x }) }),
    React.createElement(NumberInput, { label: "Duration", value: voice.duration, suffix: "s", min: .01, onChange: (x) => patch({ duration: x }) }),
    React.createElement("div", { className: "two-mini" },
        React.createElement(NumberInput, { label: "Fade in", value: voice.fadeIn, suffix: "s", min: 0, onChange: (x) => patch({ fadeIn: x }) }),
        React.createElement(NumberInput, { label: "Fade out", value: voice.fadeOut, suffix: "s", min: 0, onChange: (x) => patch({ fadeOut: x }) })),
    React.createElement(NumberInput, { label: "Duty / modulation depth", value: voice.duty, min: .01, max: .99, step: ".01", onChange: (x) => patch({ duty: x }) }),
    React.createElement("div", { className: "checks" },
        React.createElement("label", null,
            React.createElement("input", { type: "checkbox", checked: voice.loop, onChange: e => patch({ loop: e.target.checked }) }),
            " Loop"),
        React.createElement("label", null,
            React.createElement("input", { type: "checkbox", checked: voice.mute, onChange: e => patch({ mute: e.target.checked }) }),
            " Mute"),
        React.createElement("label", null,
            React.createElement("input", { type: "checkbox", checked: voice.solo, onChange: e => patch({ solo: e.target.checked }) }),
            " Solo")),
    React.createElement("h4", null, "Parameter links"),
    voice.links.map((l) => React.createElement("div", { className: "link-row", key: l.id },
        React.createElement("select", { value: l.source, onChange: e => patch({ links: voice.links.map((x) => x.id === l.id ? { ...x, source: e.target.value } : x) }) }, ['time', 'beatHz', 'carrierHz', 'amplitude'].map(x => React.createElement("option", { key: x }, x))),
        React.createElement("span", null, "\u2192"),
        React.createElement("select", { value: l.target, onChange: e => patch({ links: voice.links.map((x) => x.id === l.id ? { ...x, target: e.target.value } : x) }) }, laneParams.map(x => React.createElement("option", { key: x }, x))),
        React.createElement("input", { title: "Scale", type: "number", step: ".1", value: l.scale, onChange: e => patch({ links: voice.links.map((x) => x.id === l.id ? { ...x, scale: num(e.target.value) } : x) }) }),
        React.createElement("input", { title: "Offset", type: "number", step: ".1", value: l.offset, onChange: e => patch({ links: voice.links.map((x) => x.id === l.id ? { ...x, offset: num(e.target.value) } : x) }) }),
        React.createElement("button", { onClick: () => patch({ links: voice.links.filter((x) => x.id !== l.id) }) }, "\u00D7"))),
    React.createElement("button", { onClick: addLink }, "+ Parameter link"),
    React.createElement("details", { className: "context-help" },
        React.createElement("summary", null, "Signal help"),
        React.createElement("p", null,
            "Left/right frequencies are stored explicitly. Center carrier is ",
            (carrierOf(voice)).toFixed(3),
            " Hz and the current difference is ",
            beatOf(voice).toFixed(3),
            " Hz. A frequency label does not guarantee a psychological outcome."))); }
function NoiseInspector({ project, track, setProject }) { const patch = (x) => setProject((p) => touchProject({ ...p, noiseTracks: p.noiseTracks.map(n => n.id === track.id ? { ...n, ...x } : n) })); return React.createElement("div", { className: "studio-inspector" },
    React.createElement("h3", null, "Noise"),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Name"),
        React.createElement("input", { value: track.name, onChange: e => patch({ name: e.target.value }) })),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Color"),
        React.createElement("select", { value: track.kind, onChange: e => patch({ kind: e.target.value }) }, ['white', 'pink', 'brown', 'blue', 'violet', 'grey', 'slope'].map(x => React.createElement("option", { key: x }, x)))),
    React.createElement(NumberInput, { label: "Amplitude", value: track.amplitude, step: ".005", min: 0, max: 1, onChange: (x) => patch({ amplitude: x }) }),
    React.createElement(NumberInput, { label: "Slope", value: track.slopeDbOct, suffix: "dB/oct", min: -6, max: 6, onChange: (x) => patch({ slopeDbOct: x }) }),
    React.createElement(NumberInput, { label: "High-pass", value: track.highpass || 0, suffix: "Hz", onChange: (x) => patch({ highpass: x || undefined }) }),
    React.createElement(NumberInput, { label: "Low-pass", value: track.lowpass || 0, suffix: "Hz", onChange: (x) => patch({ lowpass: x || undefined }) }),
    React.createElement(NumberInput, { label: "Stereo correlation", value: track.stereoCorrelation, step: ".01", min: 0, max: 1, onChange: (x) => patch({ stereoCorrelation: x }) }),
    React.createElement(TrackAutomationControls, { track: track, patch: patch, parameters: ['amplitude', 'slopeDbOct', 'highpass', 'lowpass', 'stereoCorrelation'] }),
    React.createElement("details", { className: "context-help" },
        React.createElement("summary", null, "Noise help"),
        React.createElement("p", null, "Noise automation is evaluated in track-local time. Stereo correlation 0 uses independent channels; 1 shares the same stochastic component."))); }
function AudioInspector({ project, track, setProject }) { const patch = (x) => setProject((p) => touchProject({ ...p, audioTracks: p.audioTracks.map(a => a.id === track.id ? { ...a, ...x } : a) })); return React.createElement("div", { className: "studio-inspector" },
    React.createElement("h3", null, "Audio clip"),
    React.createElement("label", { className: "studio-field" },
        React.createElement("span", null, "Name"),
        React.createElement("input", { value: track.name, onChange: e => patch({ name: e.target.value }) })),
    React.createElement(NumberInput, { label: "Start", value: track.start, suffix: "s", min: 0, onChange: (x) => patch({ start: x }) }),
    React.createElement(NumberInput, { label: "Duration", value: track.duration, suffix: "s", min: .01, onChange: (x) => patch({ duration: x }) }),
    React.createElement(NumberInput, { label: "Source offset", value: track.offset, suffix: "s", min: 0, onChange: (x) => patch({ offset: x }) }),
    React.createElement(NumberInput, { label: "Level", value: track.amplitude, min: 0, max: 2, step: ".01", onChange: (x) => patch({ amplitude: x }) }),
    React.createElement(NumberInput, { label: "Pan", value: track.pan, min: -1, max: 1, step: ".01", onChange: (x) => patch({ pan: x }) }),
    React.createElement(NumberInput, { label: "Stereo width", value: track.stereoWidth ?? 1, min: 0, max: 2, step: ".01", onChange: (x) => patch({ stereoWidth: x }) }),
    React.createElement(NumberInput, { label: "Left delay", value: track.leftDelayMs || 0, suffix: "ms", min: 0, onChange: (x) => patch({ leftDelayMs: x }) }),
    React.createElement(NumberInput, { label: "Right delay", value: track.rightDelayMs || 0, suffix: "ms", min: 0, onChange: (x) => patch({ rightDelayMs: x }) }),
    React.createElement(NumberInput, { label: "High-pass", value: track.highpass || 0, suffix: "Hz", min: 0, onChange: (x) => patch({ highpass: x || undefined }) }),
    React.createElement(NumberInput, { label: "Low-pass", value: track.lowpass || 0, suffix: "Hz", min: 0, onChange: (x) => patch({ lowpass: x || undefined }) }),
    React.createElement(NumberInput, { label: "Interval", value: track.intervalSeconds || 0, suffix: "s", min: 0, onChange: (x) => patch({ intervalSeconds: x || undefined }) }),
    React.createElement(NumberInput, { label: "Interval on", value: track.intervalOnSeconds || 0, suffix: "s", min: 0, onChange: (x) => patch({ intervalOnSeconds: x || undefined }) }),
    React.createElement(TrackAutomationControls, { track: track, patch: patch, parameters: ['amplitude', 'pan', 'stereoWidth', 'leftDelayMs', 'rightDelayMs', 'highpass', 'lowpass'] }),
    React.createElement("details", { className: "context-help" },
        React.createElement("summary", null, "Background help"),
        React.createElement("p", null, "Automation and modulation are evaluated in clip-local time. Delay and width controls affect only background tracks, never the protected binaural signal bus."))); }
export function StudioSurface({ project, setProject, onPlay, playing, onSave, onExport, onUndo, onRedo, canUndo, canRedo }) { const [selection, setSelection] = React.useState({ kind: 'voice', id: project.voices[0]?.id || '' }); const [zoom, setZoom] = React.useState(1); const selectedVoice = selection.kind === 'voice' ? project.voices.find((v) => v.id === selection.id) : undefined, selectedNoise = selection.kind === 'noise' ? project.noiseTracks.find((v) => v.id === selection.id) : undefined, selectedAudio = selection.kind === 'audio' ? project.audioTracks.find((v) => v.id === selection.id) : undefined; React.useEffect(() => { if (selection.kind === 'voice' && !project.voices.some((v) => v.id === selection.id) && project.voices[0])
    setSelection({ kind: 'voice', id: project.voices[0].id }); }, [project.voices.length]); const addVoice = () => setProject((p) => { const v = createVoice(`Voice ${p.voices.length + 1}`); v.duration = p.duration; return touchProject({ ...p, voices: [...p.voices, v] }); }); const addNoise = () => setProject((p) => touchProject({ ...p, noiseTracks: [...p.noiseTracks, { id: uid('noise'), name: `Noise ${p.noiseTracks.length + 1}`, kind: 'pink', amplitude: .06, slopeDbOct: -3, stereoCorrelation: .2, start: 0, duration: p.duration, loop: true, mute: false, solo: false }] })); const duplicateSelected = () => { if (selectedVoice)
    setProject((p) => touchProject({ ...p, voices: [...p.voices, { ...structuredClone(selectedVoice), id: uid('voice'), name: selectedVoice.name + ' copy' }] }));
else if (selectedNoise)
    setProject((p) => touchProject({ ...p, noiseTracks: [...p.noiseTracks, { ...structuredClone(selectedNoise), id: uid('noise'), name: selectedNoise.name + ' copy' }] }));
else if (selectedAudio)
    setProject((p) => touchProject({ ...p, audioTracks: [...p.audioTracks, { ...structuredClone(selectedAudio), id: uid('audio'), name: selectedAudio.name + ' copy' }] })); }; const deleteSelected = () => setProject((p) => { if (selection.kind === 'voice' && p.voices.length > 1)
    return touchProject({ ...p, voices: p.voices.filter(v => v.id !== selection.id) }); if (selection.kind === 'noise')
    return touchProject({ ...p, noiseTracks: p.noiseTracks.filter(v => v.id !== selection.id) }); if (selection.kind === 'audio')
    return touchProject({ ...p, audioTracks: p.audioTracks.filter(v => v.id !== selection.id) }); return p; }); const addSegment = () => setProject((p) => { const start = p.segments.reduce((m, s) => Math.max(m, s.start + s.duration * s.repeat), 0), duration = Math.min(60, Math.max(1, p.duration)), end = start + duration, newDuration = Math.max(p.duration, end); return touchProject({ ...p, duration: newDuration, voices: p.voices.map(v => v.start + v.duration >= p.duration - .001 ? { ...v, duration: Math.max(v.duration, newDuration - v.start) } : v), noiseTracks: p.noiseTracks.map(n => n.start + n.duration >= p.duration - .001 ? { ...n, duration: Math.max(n.duration, newDuration - n.start) } : n), segments: [...p.segments, { id: uid('segment'), name: `Segment ${p.segments.length + 1}`, start, duration, repeat: 1, crossfade: .05, phaseContinuous: true }] }); }); const addMarker = () => setProject((p) => touchProject({ ...p, markers: [...p.markers, { id: uid('marker'), time: 0, label: `Marker ${p.markers.length + 1}` }] })); const total = Math.max(1, project.duration); return React.createElement("section", { className: "page studio-v2" },
    React.createElement("div", { className: "studio-v2-head" },
        React.createElement("div", null,
            React.createElement("div", { className: "eyebrow" }, "STUDIO"),
            React.createElement("input", { className: "title-edit", value: project.title, onChange: e => setProject((p) => touchProject({ ...p, title: e.target.value })) })),
        React.createElement("div", { className: "actions" },
            React.createElement("button", { onClick: onUndo, disabled: !canUndo, "aria-label": "Undo" }, "\u21B6"),
            React.createElement("button", { onClick: onRedo, disabled: !canRedo, "aria-label": "Redo" }, "\u21B7"),
            React.createElement("button", { className: "primary small", onClick: onPlay }, playing ? '■ Stop' : '▶ Play'),
            React.createElement("button", { onClick: onSave }, "Save"),
            React.createElement("div", { className: "menu" },
                React.createElement("button", null, "Export \u25BE"),
                React.createElement("div", { className: "menu-pop" },
                    React.createElement("button", { onClick: () => onExport('wav') }, "WAV 24-bit"),
                    React.createElement("button", { onClick: () => onExport('aiff') }, "AIFF 24-bit"),
                    React.createElement("button", { onClick: () => onExport('flac') }, "FLAC 24-bit"),
                    React.createElement("button", { onClick: () => onExport('mp3') }, "MP3"),
                    React.createElement("button", { onClick: () => onExport('ogg-vorbis') }, "Ogg Vorbis"),
                    React.createElement("button", { onClick: () => onExport('ogg-opus') }, "Ogg Opus"),
                    React.createElement("button", { onClick: () => onExport('webm-opus') }, "WebM Opus"),
                    React.createElement("button", { onClick: () => onExport('bbeat') }, ".bbeat project"),
                    React.createElement("button", { onClick: () => onExport('bbeat-signed') }, "Signed .bbeat"),
                    React.createElement("button", { onClick: () => onExport('bwg') }, "Legacy .bwg"),
                    React.createElement("button", { onClick: () => onExport('bwg-package') }, "Legacy BWG + WAV package"),
                    React.createElement("hr", null),
                    React.createElement("button", { onClick: () => onExport('recipe') }, "Recipe JSON"),
                    React.createElement("button", { onClick: () => onExport('manifest') }, "Stimulus manifest"),
                    React.createElement("button", { onClick: () => onExport('stems') }, "WAV stems ZIP"),
                    React.createElement("button", { onClick: () => onExport('diagnostic') }, "Diagnostic L/R WAVs"),
                    React.createElement("button", { onClick: () => onExport('wav-stimulus') }, "Stimulus-only WAV"),
                    React.createElement("button", { onClick: () => onExport('wav-background') }, "Background-only WAV"))))),
    React.createElement("div", { className: "studio-toolbar" },
        React.createElement("button", { onClick: addVoice }, "+ Voice"),
        React.createElement("button", { onClick: addNoise }, "+ Noise"),
        React.createElement("button", { onClick: duplicateSelected }, "Duplicate"),
        React.createElement("button", { onClick: deleteSelected }, "Delete"),
        React.createElement("button", { onClick: addSegment }, "+ Segment"),
        React.createElement("button", { onClick: addMarker }, "+ Marker"),
        React.createElement("label", null,
            "Zoom ",
            React.createElement("input", { type: "range", min: "1", max: "6", step: ".25", value: zoom, onChange: e => setZoom(Number(e.target.value)) })),
        React.createElement("label", null,
            "Master ",
            React.createElement("input", { type: "range", min: "0", max: "1.5", step: ".01", value: project.masterGain, onChange: e => setProject((p) => touchProject({ ...p, masterGain: Number(e.target.value) })) }))),
    React.createElement("div", { className: "studio-grid" },
        React.createElement(TrackRows, { project: project, selection: selection, setSelection: setSelection, setProject: setProject }),
        React.createElement("div", { className: "timeline-scroll" },
            React.createElement("div", { className: "timeline-v2", style: { width: `${Math.max(100, zoom * 100)}%` } },
                React.createElement("div", { className: "timeline-ruler" }, Array.from({ length: 11 }, (_, i) => React.createElement("span", { key: i, style: { left: `${i * 10}%` } },
                    Math.round(total * i / 10),
                    "s"))),
                project.markers.map((m) => React.createElement("div", { className: "marker-line", key: m.id, style: { left: `${m.time / total * 100}%` }, title: m.label })),
                project.voices.map((v) => React.createElement("div", { className: "lane-row", key: v.id },
                    React.createElement(Clip, { start: v.start, duration: v.duration, total: total, label: v.name, sub: `${v.type} · ${fmt(v.leftHz)}↔${fmt(v.rightHz)} Hz`, onChange: (x) => setProject((p) => touchProject({ ...p, voices: p.voices.map(q => q.id === v.id ? { ...q, start: x } : q) })) }))),
                project.noiseTracks.map((n) => React.createElement("div", { className: "lane-row", key: n.id },
                    React.createElement(Clip, { start: n.start, duration: n.duration, total: total, label: n.name, sub: `${n.kind} noise`, onChange: (x) => setProject((p) => touchProject({ ...p, noiseTracks: p.noiseTracks.map(q => q.id === n.id ? { ...q, start: x } : q) })) }))),
                project.audioTracks.map((a) => React.createElement("div", { className: "lane-row", key: a.id },
                    React.createElement(Clip, { start: a.start, duration: a.duration, total: total, label: a.name, sub: "imported audio", onChange: (x) => setProject((p) => touchProject({ ...p, audioTracks: p.audioTracks.map(q => q.id === a.id ? { ...q, start: x } : q) })) }))),
                selectedVoice && React.createElement(AutomationEditor, { voice: selectedVoice, project: project, setProject: setProject }),
                React.createElement("section", { className: "segment-strip" },
                    React.createElement("b", null, "Segments"),
                    project.segments.map((s, i) => React.createElement("div", { className: "segment-row", key: s.id },
                        React.createElement("input", { value: s.name, onChange: e => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, name: e.target.value } : x) })) }),
                        React.createElement(NumberInput, { label: "Start", value: s.start, min: 0, suffix: "s", onChange: (v) => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, start: v } : x) })) }),
                        React.createElement(NumberInput, { label: "Duration", value: s.duration, min: .01, suffix: "s", onChange: (v) => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, duration: v } : x) })) }),
                        React.createElement(NumberInput, { label: "Repeat", value: s.repeat, min: 1, step: 1, onChange: (v) => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, repeat: Math.max(1, Math.round(v)) } : x) })) }),
                        React.createElement(NumberInput, { label: "Crossfade", value: s.crossfade, min: 0, suffix: "s", onChange: (v) => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, crossfade: v } : x) })) }),
                        React.createElement("label", { className: "compact-field" },
                            "Scope",
                            React.createElement("select", { value: s.trackIds?.length === 1 ? s.trackIds[0] : 'all', onChange: e => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, trackIds: e.target.value === 'all' ? undefined : [e.target.value] } : x) })) },
                                React.createElement("option", { value: "all" }, "All tracks"),
                                project.voices.map((v) => React.createElement("option", { value: v.id, key: v.id }, v.name)),
                                project.noiseTracks.map((n) => React.createElement("option", { value: n.id, key: n.id }, n.name)),
                                project.audioTracks.map((a) => React.createElement("option", { value: a.id, key: a.id }, a.name)))),
                        React.createElement("label", { className: "compact-field" },
                            "Beat override",
                            React.createElement("input", { type: "number", step: ".01", placeholder: "none", value: s.overrides?.beatHz ?? '', onChange: e => setProject((p) => touchProject({ ...p, segments: p.segments.map(x => x.id === s.id ? { ...x, overrides: e.target.value === '' ? { ...(x.overrides || {}), beatHz: undefined } : { ...(x.overrides || {}), beatHz: Number(e.target.value) } } : x) })) })),
                        React.createElement("button", { disabled: i === 0, onClick: () => setProject((p) => { const a = p.segments.slice(), j = a.findIndex(x => x.id === s.id); [a[j - 1], a[j]] = [a[j], a[j - 1]]; return touchProject({ ...p, segments: a }); }) }, "\u2191"),
                        React.createElement("button", { onClick: () => setProject((p) => touchProject({ ...p, segments: [...p.segments, { ...structuredClone(s), id: uid('segment'), name: s.name + ' copy' }] })) }, "\u29C9")))),
                React.createElement("section", { className: "marker-strip" },
                    React.createElement("b", null, "Markers"),
                    project.markers.map((m) => React.createElement("div", { key: m.id },
                        React.createElement("input", { value: m.label, onChange: e => setProject((p) => touchProject({ ...p, markers: p.markers.map(x => x.id === m.id ? { ...x, label: e.target.value } : x) })) }),
                        React.createElement("input", { type: "number", min: "0", max: total, step: ".01", value: m.time, onChange: e => setProject((p) => touchProject({ ...p, markers: p.markers.map(x => x.id === m.id ? { ...x, time: num(e.target.value) } : x) })) }),
                        React.createElement("button", { onClick: () => setProject((p) => touchProject({ ...p, markers: p.markers.filter(x => x.id !== m.id) })) }, "\u00D7")))))),
        selectedVoice ? React.createElement(VoiceInspector, { project: project, voice: selectedVoice, setProject: setProject }) : selectedNoise ? React.createElement(NoiseInspector, { project: project, track: selectedNoise, setProject: setProject }) : selectedAudio ? React.createElement(AudioInspector, { project: project, track: selectedAudio, setProject: setProject }) : React.createElement("div", { className: "studio-inspector" },
            React.createElement("p", null, "Select a track.")))); }
//# sourceMappingURL=StudioSurface.js.map