import { uid } from '../core/types.js';
import { beatOf, carrierOf, createVoice, touchProject } from '../core/project.js';
const voiceParams = ['beatHz', 'carrierHz', 'leftHz', 'rightHz', 'amplitude', 'duty'];
const curves = ['hold', 'linear', 'smooth', 'exponential', 'logarithmic', 'bezier'];
const n = (v, f = 0) => Number.isFinite(Number(v)) ? Number(v) : f;
function HelpTip({ children }) { return React.createElement("span", { className: "studio-help", tabIndex: 0, title: children, "aria-label": `Help: ${children}` }, "?"); }
function Field({ label, value, onChange, min, max, step = .01, suffix, help }) { return React.createElement("label", { className: "studio-field" },
    React.createElement("span", null,
        label,
        help && React.createElement(HelpTip, null, help)),
    React.createElement("div", { className: "input-suffix" },
        React.createElement("input", { type: "number", value: Number.isFinite(value) ? value : '', min: min, max: max, step: step, onChange: e => onChange(n(e.target.value, value)) }),
        suffix && React.createElement("i", null, suffix))); }
function TrackList({ project, selection, setSelection, setProject }) { const toggle = (kind, id, key) => setProject((p) => touchProject({ ...p, [kind]: p[kind].map((x) => x.id === id ? { ...x, [key]: !x[key] } : x) })); const row = (kind, key, label, sub, mute, solo) => React.createElement("div", { className: `studio-track-row ${selection.kind === kind && selection.id === key ? 'selected' : ''}`, key: key, onClick: () => setSelection({ kind, id: key }) },
    React.createElement("button", { className: "track-main", title: `Select ${label}` },
        React.createElement("b", null, label),
        React.createElement("small", null, sub)),
    React.createElement("button", { className: mute ? 'tiny active' : 'tiny', "aria-label": `Mute ${label}`, onClick: e => { e.stopPropagation(); toggle(kind === 'voice' ? 'voices' : kind === 'noise' ? 'noiseTracks' : 'audioTracks', key, 'mute'); } }, "M"),
    React.createElement("button", { className: solo ? 'tiny active' : 'tiny', "aria-label": `Solo ${label}`, onClick: e => { e.stopPropagation(); toggle(kind === 'voice' ? 'voices' : kind === 'noise' ? 'noiseTracks' : 'audioTracks', key, 'solo'); } }, "S")); return React.createElement("div", { className: "studio-track-list", role: "listbox", "aria-label": "Timeline tracks" },
    React.createElement("div", { className: "track-group-label" }, "SOUND"),
    project.voices.map((v) => row('voice', v.id, v.name, `${v.type} · ${beatOf(v).toFixed(2)} Hz`, v.mute, v.solo)),
    project.audioTracks.length > 0 && React.createElement("div", { className: "track-group-label" }, "BACKGROUND AUDIO"),
    project.audioTracks.map((a) => row('audio', a.id, a.name, 'imported audio', a.mute, a.solo)),
    project.noiseTracks.length > 0 && React.createElement("div", { className: "track-group-label" }, "NOISE / BACKGROUND"),
    project.noiseTracks.map((a) => row('noise', a.id, a.name, `${a.kind} noise`, a.mute, a.solo))); }
function Clip({ start, duration, total, label, sub, onChange, color = 'blue' }) { const drag = React.useRef(null); const down = (e) => { if (e.button !== 0)
    return; drag.current = { x: e.clientX, start }; const move = (m) => { if (!drag.current)
    return; const el = e.currentTarget.parentElement, w = Math.max(1, el.getBoundingClientRect().width), dt = (m.clientX - drag.current.x) / w * total; onChange(Math.max(0, Math.min(total - duration, drag.current.start + dt))); }; const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); drag.current = null; }; addEventListener('pointermove', move); addEventListener('pointerup', up); }; return React.createElement("div", { className: `timeline-clip ${color}`, onPointerDown: down, style: { left: `${start / total * 100}%`, width: `${Math.max(1, duration / total * 100)}%` }, title: `${label}: starts at ${start.toFixed(2)} seconds, lasts ${duration.toFixed(2)} seconds` },
    React.createElement("b", null, label),
    React.createElement("small", null, sub)); }
function TimeCurve({ voice, project, setProject }) { const [parameter, setParameter] = React.useState('beatHz'); const lane = voice.automation.find((x) => x.parameter === parameter); const fallback = parameter === 'beatHz' ? beatOf(voice) : parameter === 'carrierHz' ? carrierOf(voice) : parameter === 'leftHz' ? voice.leftHz : parameter === 'rightHz' ? voice.rightHz : parameter === 'amplitude' ? voice.amplitude : voice.duty; const points = (lane?.points?.length ? lane.points : [{ id: 'default-a', time: 0, value: fallback, curve: 'linear' }, { id: 'default-b', time: voice.duration, value: fallback, curve: 'linear' }]); const vals = points.map(p => p.value), lo = Math.min(...vals, fallback), hi = Math.max(...vals, fallback), pad = Math.max((hi - lo) * .2, .01), yMin = lo - pad, yMax = hi + pad; const update = (ps) => setProject((p) => touchProject({ ...p, voices: p.voices.map(v => v.id === voice.id ? { ...v, automation: [...v.automation.filter(a => a.parameter !== parameter), { parameter, points: ps.sort((a, b) => a.time - b.time) }] } : v) })); const add = (e) => { const r = e.currentTarget.getBoundingClientRect(), time = Math.max(0, Math.min(voice.duration, (e.clientX - r.left) / r.width * voice.duration)), value = yMax - (e.clientY - r.top) / r.height * (yMax - yMin); update([...(lane?.points || []), { id: uid('point'), time, value, curve: 'linear' }]); }; const real = lane?.points || []; const path = points.map((p, i) => `${i ? 'L' : 'M'} ${(p.time / Math.max(.001, voice.duration)) * 800} ${100 - (p.value - yMin) / (yMax - yMin) * 100}`).join(' '); return React.createElement("section", { className: "time-shaping" },
    React.createElement("div", { className: "section-head" },
        React.createElement("div", null,
            React.createElement("h3", null,
                "Time shaping ",
                React.createElement(HelpTip, null, "Shape one parameter across this track\u2019s full duration. Points use track-local time, so playback behavior stays unchanged.")),
            React.createElement("small", null,
                "Track-local timeline \u00B7 0:00 to ",
                voice.duration.toFixed(2),
                " s")),
        React.createElement("select", { "aria-label": "Time shaping parameter", value: parameter, onChange: e => setParameter(e.target.value) }, voiceParams.map(x => React.createElement("option", { key: x }, x)))),
    React.createElement("div", { className: "curve-toolbar" },
        React.createElement("span", null, "Double-click to add"),
        React.createElement("span", null, "Drag a point to move it"),
        React.createElement("span", null, "Use the table for exact values"),
        React.createElement("button", { onClick: () => update([]), disabled: !lane }, "Clear curve")),
    React.createElement("svg", { className: "time-curve", viewBox: "0 0 800 120", preserveAspectRatio: "none", onDoubleClick: add, "aria-label": `${parameter} time shaping graph` },
        React.createElement("path", { d: path, fill: "none", stroke: "currentColor", strokeWidth: "3" }),
        points.map(p => React.createElement("circle", { key: p.id, cx: (p.time / Math.max(.001, voice.duration)) * 800, cy: 120 - (p.value - yMin) / (yMax - yMin) * 120, r: "7" }))),
    React.createElement("div", { className: "time-axis" },
        React.createElement("span", null, "0:00"),
        React.createElement("span", null,
            (voice.duration / 2).toFixed(1),
            "s"),
        React.createElement("span", null,
            voice.duration.toFixed(1),
            "s")),
    real.length > 0 && React.createElement("div", { className: "automation-table" }, real.map(p => React.createElement("div", { key: p.id },
        React.createElement("input", { "aria-label": "Time point seconds", title: "Time in seconds", type: "number", min: "0", max: voice.duration, step: ".01", value: p.time, onChange: e => update(real.map(q => q.id === p.id ? { ...q, time: Math.max(0, Math.min(voice.duration, n(e.target.value))) } : q)) }),
        React.createElement("input", { "aria-label": "Time point value", title: "Parameter value", type: "number", step: ".01", value: p.value, onChange: e => update(real.map(q => q.id === p.id ? { ...q, value: n(e.target.value) } : q)) }),
        React.createElement("select", { "aria-label": "Curve interpolation", value: p.curve, onChange: e => update(real.map(q => q.id === p.id ? { ...q, curve: e.target.value } : q)) }, curves.map(c => React.createElement("option", { key: c }, c))),
        React.createElement("button", { "aria-label": "Delete time point", onClick: () => update(real.filter(q => q.id !== p.id)) }, "\u00D7"))))); }
function Inspector({ project, selection, setProject }) { const voice = selection.kind === 'voice' ? project.voices.find((v) => v.id === selection.id) : undefined; const noise = selection.kind === 'noise' ? project.noiseTracks.find((v) => v.id === selection.id) : undefined; const audio = selection.kind === 'audio' ? project.audioTracks.find((v) => v.id === selection.id) : undefined; const patch = (x) => setProject((p) => touchProject({ ...p, voices: p.voices.map(v => v.id === voice?.id ? { ...v, ...x } : v), noiseTracks: p.noiseTracks.map(v => v.id === noise?.id ? { ...v, ...x } : v), audioTracks: p.audioTracks.map(v => v.id === audio?.id ? { ...v, ...x } : v) })); if (voice)
    return React.createElement("div", { className: "studio-inspector" },
        React.createElement("h3", null, voice.name),
        React.createElement("p", { className: "inspector-lede" }, "The selected track\u2019s sound and timing."),
        React.createElement("label", { className: "studio-field" },
            React.createElement("span", null, "Name"),
            React.createElement("input", { value: voice.name, onChange: e => patch({ name: e.target.value }) })),
        React.createElement(Field, { label: "Left ear", value: voice.leftHz, suffix: "Hz", min: .001, onChange: (x) => patch({ leftHz: x }) }),
        React.createElement(Field, { label: "Right ear", value: voice.rightHz, suffix: "Hz", min: .001, onChange: (x) => patch({ rightHz: x }) }),
        React.createElement(Field, { label: "Amplitude", value: voice.amplitude, min: 0, max: 2, onChange: (x) => patch({ amplitude: x }) }),
        React.createElement(Field, { label: "Start", value: voice.start, suffix: "s", min: 0, onChange: (x) => patch({ start: x }) }),
        React.createElement(Field, { label: "Tone length", value: voice.duration, suffix: "s", min: .01, onChange: (x) => patch({ duration: x }) }),
        React.createElement("div", { className: "checks" },
            React.createElement("label", null,
                React.createElement("input", { type: "checkbox", checked: voice.loop, onChange: e => patch({ loop: e.target.checked }) }),
                " Loop track"),
            React.createElement("label", null,
                React.createElement("input", { type: "checkbox", checked: voice.mute, onChange: e => patch({ mute: e.target.checked }) }),
                " Mute"),
            React.createElement("label", null,
                React.createElement("input", { type: "checkbox", checked: voice.solo, onChange: e => patch({ solo: e.target.checked }) }),
                " Solo")),
        React.createElement("details", { className: "context-help" },
            React.createElement("summary", null, "How this works"),
            React.createElement("p", null, "Left and right frequencies are explicit. The tone length controls the clip and the time-shaping editor below uses that same duration."))); if (noise)
    return React.createElement("div", { className: "studio-inspector" },
        React.createElement("h3", null, noise.name),
        React.createElement("p", { className: "inspector-lede" }, "Procedural background layer."),
        React.createElement("label", { className: "studio-field" },
            React.createElement("span", null, "Noise color"),
            React.createElement("select", { value: noise.kind, onChange: e => patch({ kind: e.target.value }) }, ['white', 'pink', 'brown', 'blue', 'violet', 'grey', 'slope'].map(x => React.createElement("option", { key: x }, x)))),
        React.createElement(Field, { label: "Level", value: noise.amplitude, min: 0, max: 1, onChange: (x) => patch({ amplitude: x }) }),
        React.createElement(Field, { label: "Start", value: noise.start, suffix: "s", min: 0, onChange: (x) => patch({ start: x }) }),
        React.createElement(Field, { label: "Layer length", value: noise.duration, suffix: "s", min: .01, onChange: (x) => patch({ duration: x }) }),
        React.createElement("label", { className: "checks" },
            React.createElement("input", { type: "checkbox", checked: !!noise.invertRight, onChange: e => patch({ invertRight: e.target.checked }) }),
            " Invert right channel"),
        React.createElement("details", { className: "context-help" },
            React.createElement("summary", null, "How this works"),
            React.createElement("p", null, "Background layers stay on the protected background bus and never replace the binaural voice."))); if (audio)
    return React.createElement("div", { className: "studio-inspector" },
        React.createElement("h3", null, audio.name),
        React.createElement("p", { className: "inspector-lede" }, "Imported background clip."),
        React.createElement(Field, { label: "Start", value: audio.start, suffix: "s", min: 0, onChange: (x) => patch({ start: x }) }),
        React.createElement(Field, { label: "Clip length", value: audio.duration, suffix: "s", min: .01, onChange: (x) => patch({ duration: x }) }),
        React.createElement(Field, { label: "Level", value: audio.amplitude, min: 0, max: 2, onChange: (x) => patch({ amplitude: x }) }),
        React.createElement(Field, { label: "Pan", value: audio.pan, min: -1, max: 1, onChange: (x) => patch({ pan: x }) }),
        React.createElement("label", { className: "checks" },
            React.createElement("input", { type: "checkbox", checked: audio.loop, onChange: e => patch({ loop: e.target.checked }) }),
            " Loop clip")); return React.createElement("div", { className: "studio-inspector empty-inspector" },
    React.createElement("h3", null, "Select a track"),
    React.createElement("p", null, "Choose a track on the left to edit its timing and sound.")); }
export function StudioTimelineSurface({ project, setProject, onPlay, playing, paused, onSave, onExport, onUndo, onRedo, canUndo, canRedo }) { const first = project.voices[0] ? { kind: 'voice', id: project.voices[0].id } : project.audioTracks[0] ? { kind: 'audio', id: project.audioTracks[0].id } : { kind: 'noise', id: project.noiseTracks[0]?.id || '' }; const [selection, setSelection] = React.useState(first); const [zoom, setZoom] = React.useState(1); const selectedVoice = selection.kind === 'voice' ? project.voices.find((v) => v.id === selection.id) : undefined; React.useEffect(() => { const exists = (selection.kind === 'voice' ? project.voices : selection.kind === 'noise' ? project.noiseTracks : project.audioTracks).some((x) => x.id === selection.id); if (!exists)
    setSelection(first); }, [project.voices.length, project.noiseTracks.length, project.audioTracks.length]); const total = Math.max(1, project.duration); const width = Math.max(100, zoom * 100); const addVoice = () => setProject((p) => { const v = createVoice(`Voice ${p.voices.length + 1}`); v.duration = p.duration; return touchProject({ ...p, voices: [...p.voices, v] }); }); const addNoise = () => setProject((p) => touchProject({ ...p, noiseTracks: [...p.noiseTracks, { id: uid('noise'), name: `Noise ${p.noiseTracks.length + 1}`, kind: 'pink', amplitude: .06, slopeDbOct: -3, stereoCorrelation: .2, invertRight: false, start: 0, duration: p.duration, loop: true, mute: false, solo: false }] })); return React.createElement("section", { className: "page studio-v3" },
    React.createElement("div", { className: "studio-v3-head" },
        React.createElement("div", null,
            React.createElement("div", { className: "eyebrow" }, "STUDIO"),
            React.createElement("h1", null, "Build your sound over time"),
            React.createElement("p", { className: "lede" }, "Arrange tones and background layers on a clear, zoomable timeline. Every curve is evaluated against the track\u2019s own duration.")),
        React.createElement("div", { className: "actions" },
            React.createElement("button", { onClick: onUndo, disabled: !canUndo, title: "Undo last Studio edit" }, "\u21B6"),
            React.createElement("button", { onClick: onRedo, disabled: !canRedo, title: "Redo last Studio edit" }, "\u21B7"),
            React.createElement("button", { className: "primary", onClick: onPlay }, playing ? '■ Stop' : '▶ Play'),
            React.createElement("button", { onClick: onSave }, "Save"))),
    React.createElement("div", { className: "studio-v3-toolbar" },
        React.createElement("button", { onClick: addVoice }, "\uFF0B Tone"),
        React.createElement("button", { onClick: addNoise }, "\uFF0B Background"),
        React.createElement("button", { onClick: () => setProject((p) => touchProject({ ...p, duration: Math.max(p.duration, project.duration + 60) })) }, "\uFF0B 1 min"),
        React.createElement("label", { className: "zoom-control" },
            React.createElement("span", null,
                "Timeline zoom ",
                React.createElement(HelpTip, null, "Zoom changes the visible working width, not the project duration or audio timing.")),
            React.createElement("input", { type: "range", min: ".5", max: "6", step: ".25", value: zoom, onChange: e => setZoom(Number(e.target.value)) }),
            React.createElement("b", null,
                zoom.toFixed(2),
                "\u00D7")),
        React.createElement("div", { className: "time-readout" },
            "0:00 \u2014 ",
            Math.floor(total / 60),
            ":",
            String(Math.round(total % 60)).padStart(2, '0'))),
    React.createElement("div", { className: "studio-v3-grid" },
        React.createElement(TrackList, { project: project, selection: selection, setSelection: setSelection, setProject: setProject }),
        React.createElement("div", { className: "timeline-scroll" },
            React.createElement("div", { className: `timeline-v3${playing ? " is-playing" : ""}${paused ? " is-paused" : ""}`, style: { width: `${width}%`, '--playhead-duration': `${total}s` } },
                React.createElement("div", { className: "timeline-playhead", "aria-label": "Playback position" }),
                React.createElement("div", { className: "timeline-ruler" }, Array.from({ length: Math.min(25, Math.max(5, Math.ceil(total / Math.max(1, 60 / zoom))) + 1) }, (_, i) => { const t = total * i / (Math.min(25, Math.max(5, Math.ceil(total / Math.max(1, 60 / zoom))))); return React.createElement("span", { key: i, style: { left: `${i / (Math.min(25, Math.max(5, Math.ceil(total / Math.max(1, 60 / zoom))))) * 100}%` } },
                    Math.floor(t / 60),
                    ":",
                    String(Math.round(t % 60)).padStart(2, '0')); })),
                project.voices.map((v) => React.createElement("div", { className: "lane-row", key: v.id },
                    React.createElement(Clip, { start: v.start, duration: v.duration, total: total, label: v.name, sub: `${v.leftHz.toFixed(1)} ↔ ${v.rightHz.toFixed(1)} Hz`, onChange: (x) => setProject((p) => touchProject({ ...p, voices: p.voices.map(q => q.id === v.id ? { ...q, start: x } : q) })) }))),
                project.audioTracks.map((a) => React.createElement("div", { className: "lane-row", key: a.id },
                    React.createElement(Clip, { start: a.start, duration: a.duration, total: total, label: a.name, sub: "background audio", color: "green", onChange: (x) => setProject((p) => touchProject({ ...p, audioTracks: p.audioTracks.map(q => q.id === a.id ? { ...q, start: x } : q) })) }))),
                project.noiseTracks.map((a) => React.createElement("div", { className: "lane-row", key: a.id },
                    React.createElement(Clip, { start: a.start, duration: a.duration, total: total, label: a.name, sub: `${a.kind} background`, color: "purple", onChange: (x) => setProject((p) => touchProject({ ...p, noiseTracks: p.noiseTracks.map(q => q.id === a.id ? { ...q, start: x } : q) })) }))))),
        React.createElement(Inspector, { project: project, selection: selection, setProject: setProject })),
    selectedVoice && React.createElement(TimeCurve, { voice: selectedVoice, project: project, setProject: setProject }),
    React.createElement("div", { className: "studio-guide" },
        React.createElement("span", { className: "guide-dot blue" }),
        React.createElement("b", null, "Sound"),
        React.createElement("span", { className: "guide-dot green" }),
        React.createElement("b", null, "Background audio"),
        React.createElement("span", { className: "guide-dot purple" }),
        React.createElement("b", null, "Procedural noise"),
        React.createElement("span", null, "Drag clips to move them \u00B7 select a track for details \u00B7 hover ? for help"))); }
//# sourceMappingURL=StudioTimelineSurface.js.map