import {LightControlSpec,Project,VisualSpec} from '../core/types.js';
import {touchProject} from '../core/project.js';
import {analyzeLightControl,DEFAULT_LIGHT_CONTROL,renderLightControl} from '../labs/lightControl.js';
import {encodeWav} from '../formats/wav.js';

function download(name:string,bytes:Uint8Array,type='audio/wav'){const u=URL.createObjectURL(new Blob([bytes as BlobPart],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function N({label,value,onChange,min=0,max=100,step=.01,suffix=''}:any){return <label className="studio-field"><span>{label}</span><input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><small>{suffix}</small></label>}
function Curve({left,right,onChange}:any){return <div className="visual-curve" aria-label="Visual brightness curve"><svg viewBox="0 0 300 80"><path d="M0 60 C70 10 150 70 220 20 S280 30 300 10"/><circle cx={left*300} cy={60-left*45} r="5"/><circle cx={right*300} cy={60-right*45} r="5"/></svg><input aria-label="Left brightness" type="range" min="0" max="1" step=".01" value={left} onChange={e=>onChange({left:Number(e.target.value)})}/><input aria-label="Right brightness" type="range" min="0" max="1" step=".01" value={right} onChange={e=>onChange({right:Number(e.target.value)})}/></div>}
async function estimateRefresh(){return new Promise<number>(resolve=>{let last=0;const xs:number[]=[];const f=(t:number)=>{if(last)xs.push(t-last);last=t;if(xs.length===30)resolve(1000/(xs.reduce((a,b)=>a+b,0)/xs.length));else requestAnimationFrame(f)};requestAnimationFrame(f)})}

export function LabsSurface({setMessage,project,setProject}:any){
 const fallback:VisualSpec={frequencyHz:10,duty:.5,waveform:'square',leftBrightness:.72,rightBrightness:.72,leftPhase:0,rightPhase:0};
 const [localVisual,setLocalVisual]=React.useState<VisualSpec>(()=>({...fallback,...(project?.visual||{})}));
 const visual:VisualSpec={...fallback,...(project?.visual||localVisual)};
 const [armed,setArmed]=React.useState(false),[on,setOn]=React.useState(false),[refresh,setRefresh]=React.useState<number|null>(null),[spec,setSpec]=React.useState<LightControlSpec>({...DEFAULT_LIGHT_CONTROL}),[duration,setDuration]=React.useState(60),[rate,setRate]=React.useState(48000),[diag,setDiag]=React.useState<any>(null);
 const patchVisual=(x:Partial<VisualSpec>)=>{const next={...visual,...x};if(setProject)setProject((p:Project)=>touchProject({...p,visual:next}));else setLocalVisual(next)};
 const patch=(x:Partial<LightControlSpec>)=>setSpec(s=>({...s,...x}));
 const hz=Math.min(visual.frequencyHz,refresh?refresh/2:visual.frequencyHz);
 React.useEffect(()=>{estimateRefresh().then(setRefresh).catch(()=>{})},[]);
 React.useEffect(()=>{if(!armed||visual.waveform!=='square'){setOn(false);return}let stop=false,t:any;const loop=()=>{if(stop)return;setOn(true);t=setTimeout(()=>{setOn(false);t=setTimeout(loop,1000/hz*(1-visual.duty))},1000/hz*visual.duty)};loop();return()=>{stop=true;clearTimeout(t)}},[armed,visual.waveform,hz,visual.duty]);
 const render=()=>{try{const b=renderLightControl(duration,rate,spec);setDiag(analyzeLightControl(b));return b}catch(e){setMessage?.(String(e));return null}};
 const exportWav=()=>{const b=render();if(b){download(`light-control-${spec.frequencyHz}hz.wav`,encodeWav(b,24));setMessage?.('Lossless legacy light-control WAV exported.')}};
 return <section className="page"><div className="eyebrow">LABS</div><h1>Visual & legacy light-control laboratory</h1><div className="warning"><b>Photosensitive seizure warning</b><p>Flashing light can trigger seizures. Enable it only after acknowledging this warning; browser timing is not laboratory calibrated.</p><label><input type="checkbox" checked={armed} onChange={e=>setArmed(e.target.checked)}/> I understand and want to enable visual flicker controls</label></div><div className="labs-grid">
 <div className="lab-card"><h3>Visual stimulation</h3><p>Refresh: <b>{refresh?`${refresh.toFixed(1)} Hz`:'measuring…'}</b>. Separate brightness and phase controls follow the reference workflow.</p><N label="Frequency" value={visual.frequencyHz} min={.5} max={Math.max(1,(refresh||60)/2)} step={.1} suffix="Hz" onChange={(x:number)=>patchVisual({frequencyHz:x})}/><N label="Duty cycle" value={visual.duty} min={.05} max={.95} onChange={(x:number)=>patchVisual({duty:x})}/><label className="studio-field"><span>Waveform</span><select value={visual.waveform} onChange={e=>patchVisual({waveform:e.target.value as any})}><option value="square">Square</option><option value="sine">Sine</option></select></label><h4>Brightness curve</h4><Curve left={visual.leftBrightness} right={visual.rightBrightness} onChange={(x:any)=>patchVisual({leftBrightness:x.left??visual.leftBrightness,rightBrightness:x.right??visual.rightBrightness})}/><div className="two-mini"><N label="Left brightness" value={visual.leftBrightness} max={1} onChange={(x:number)=>patchVisual({leftBrightness:x})}/><N label="Right brightness" value={visual.rightBrightness} max={1} onChange={(x:number)=>patchVisual({rightBrightness:x})}/></div><N label="Phase difference" value={visual.rightPhase-visual.leftPhase} min={-6.283} max={6.283} suffix="rad" onChange={(x:number)=>patchVisual({rightPhase:visual.leftPhase+x})}/><label className="studio-field"><span>Phase mode</span><select value={visual.rightPhase===visual.leftPhase?'in':'custom'} onChange={e=>e.target.value==='in'&&patchVisual({rightPhase:visual.leftPhase})}><option value="in">In phase</option><option value="custom">Custom phase difference</option></select></label><div className="visual-preview" style={armed?{opacity:Math.max(visual.leftBrightness,visual.rightBrightness),['--visual-on-opacity' as any]:on?'1':'0'}:undefined}><span>{armed?`${hz.toFixed(2)} Hz · ${Math.round(visual.duty*100)}% ${visual.waveform}`:'Safety interlock off'}</span></div><small>Project visual settings persist in the current session; timing remains provisional.</small></div>
 <div className="lab-card"><h3>Legacy 19.2 kHz Light Control</h3><p>Creates one amplitude-gated 19.2 kHz carrier per stereo channel. Keep it lossless.</p><N label="Light modulation" value={spec.frequencyHz} min={.1} max={40} suffix="Hz" onChange={(x:number)=>patch({frequencyHz:x})}/><N label="Left amplitude" value={spec.leftAmplitude} max={.8} onChange={(x:number)=>patch({leftAmplitude:x})}/><N label="Right amplitude" value={spec.rightAmplitude} max={.8} onChange={(x:number)=>patch({rightAmplitude:x})}/><N label="Left phase" value={spec.leftPhase} min={-6.283} max={6.283} suffix="rad" onChange={(x:number)=>patch({leftPhase:x})}/><N label="Right phase" value={spec.rightPhase} min={-6.283} max={6.283} suffix="rad" onChange={(x:number)=>patch({rightPhase:x})}/><N label="Duty cycle" value={spec.duty} min={.01} max={.99} onChange={(x:number)=>patch({duty:x})}/><label className="studio-field"><span>Waveform</span><select value={spec.waveform} onChange={e=>patch({waveform:e.target.value as any})}><option value="square">Square gate</option><option value="sine">Sine gate</option></select></label><N label="Duration" value={duration} min={.1} max={3600} step={1} suffix="s" onChange={setDuration}/><label className="studio-field"><span>Sample rate</span><select value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="44100">44.1 kHz</option><option value="48000">48 kHz</option><option value="96000">96 kHz</option><option value="192000">192 kHz</option></select></label><div className="actions"><button onClick={render}>Validate signal</button><button className="primary small" onClick={exportWav}>Export lossless WAV</button></div>{diag&&<div className="technical"><b>{diag.present?'19.2 kHz carrier detected':'Carrier validation failed'}</b></div>}</div>
 <div className="lab-card"><h3>Compatibility validation</h3><p>Software validation covers carrier, envelope, duty, phase, channel mapping and lossless export. Physical decoder validation remains external.</p><div className="chips"><span>Software signal validation</span><span>Lossless reference export</span></div></div></div></section>;
}
