import {LightControlSpec,StereoBuffer} from '../core/types.js';
import {analyzeLightControl,DEFAULT_LIGHT_CONTROL,renderLightControl} from '../labs/lightControl.js';
import {encodeWav} from '../formats/wav.js';
function download(name:string,bytes:Uint8Array,type='audio/wav'){const u=URL.createObjectURL(new Blob([bytes as BlobPart],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function N({label,value,onChange,min=0,max=100,step=.01,suffix=''}:any){return <label className="studio-field"><span>{label}</span><input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><small>{suffix}</small></label>}
async function estimateRefresh(samples=45){return new Promise<number>(resolve=>{let last=0,vals:number[]=[];const tick=(t:number)=>{if(last)vals.push(t-last);last=t;if(vals.length>=samples){const avg=vals.reduce((a,b)=>a+b,0)/vals.length;resolve(1000/avg)}else requestAnimationFrame(tick)};requestAnimationFrame(tick)})}
export function LabsSurface({setMessage}:any){const [armed,setArmed]=React.useState(false),[visualHz,setVisualHz]=React.useState(10),[visualDuty,setVisualDuty]=React.useState(.5),[visualWave,setVisualWave]=React.useState<'square'|'sine'>('square'),[brightness,setBrightness]=React.useState(.72),[refresh,setRefresh]=React.useState<number|null>(null),[spec,setSpec]=React.useState<LightControlSpec>({...DEFAULT_LIGHT_CONTROL}),[duration,setDuration]=React.useState(60),[rate,setRate]=React.useState(48000),[diag,setDiag]=React.useState<any>(null);const patch=(p:Partial<LightControlSpec>)=>setSpec(s=>({...s,...p}));const effectiveHz=refresh&&visualWave==='square'?Math.max(.5,Math.min(visualHz,refresh/2)):visualHz;
 React.useEffect(()=>{estimateRefresh().then(setRefresh).catch(()=>{})},[]);
 const render=()=>{try{const b=renderLightControl(duration,rate,spec);setDiag(analyzeLightControl(b));return b}catch(e){setMessage?.(e instanceof Error?e.message:String(e));return null}};
 const exportWav=()=>{const b=render();if(!b)return;download(`light-control-${spec.frequencyHz}hz.wav`,encodeWav(b,24));setMessage?.('Lossless 24-bit legacy light-control WAV exported. Do not use lossy encoding on the 19.2 kHz carrier.');};
 return <section className="page"><div className="eyebrow">LABS</div><h1>Visual & legacy light-control laboratory</h1><div className="warning"><b>Photosensitive seizure warning</b><p>Flashing light can trigger seizures in susceptible people. Enable it only after acknowledging this warning; stop immediately if you feel unwell. Display timing is not laboratory calibrated.</p><label><input type="checkbox" checked={armed} onChange={e=>setArmed(e.target.checked)}/> I understand and want to enable visual flicker controls</label></div>
 <div className="labs-grid"><div className="lab-card"><h3>Visual stimulation</h3><p>Measured display refresh: <b>{refresh?`${refresh.toFixed(1)} Hz`:'measuring…'}</b>. Requested patterns are bounded by observable refresh timing.</p><N label="Frequency" value={visualHz} min={.5} max={Math.max(1,(refresh||60)/2)} step={.1} suffix="Hz" onChange={setVisualHz}/><N label="Duty cycle" value={visualDuty} min={.05} max={.95} step={.01} onChange={setVisualDuty}/><N label="Brightness" value={brightness} min={.05} max={1} step={.01} onChange={setBrightness}/><label className="studio-field"><span>Waveform</span><select value={visualWave} onChange={e=>setVisualWave(e.target.value as any)}><option value="square">Square</option><option value="sine">Sine</option></select></label><div className={`visual-preview ${armed?'armed':''}`} style={armed?{['--visual-period' as any]:`${1/effectiveHz}s`,['--visual-duty' as any]:`${visualDuty*100}%`,opacity:brightness}:undefined}><span>{armed?`${effectiveHz.toFixed(2)} Hz preview`:'Safety interlock off'}</span></div><small>Browser scheduling, display response, compositing and refresh rate prevent a laboratory-precision timing claim.</small></div>
 <div className="lab-card"><h3>Legacy 19.2 kHz Light Control</h3><p>Creates one amplitude-gated 19.2 kHz control carrier per stereo channel for compatible legacy decoders. Keep this path lossless.</p><N label="Light modulation" value={spec.frequencyHz} min={.1} max={40} step={.1} suffix="Hz" onChange={(x:number)=>patch({frequencyHz:x})}/><N label="Left amplitude" value={spec.leftAmplitude} min={0} max={.8} step={.01} onChange={(x:number)=>patch({leftAmplitude:x})}/><N label="Right amplitude" value={spec.rightAmplitude} min={0} max={.8} step={.01} onChange={(x:number)=>patch({rightAmplitude:x})}/><N label="Left phase" value={spec.leftPhase} min={-6.283} max={6.283} step={.01} suffix="rad" onChange={(x:number)=>patch({leftPhase:x})}/><N label="Right phase" value={spec.rightPhase} min={-6.283} max={6.283} step={.01} suffix="rad" onChange={(x:number)=>patch({rightPhase:x})}/><N label="Duty cycle" value={spec.duty} min={.01} max={.99} step={.01} onChange={(x:number)=>patch({duty:x})}/><label className="studio-field"><span>Waveform</span><select value={spec.waveform} onChange={e=>patch({waveform:e.target.value as any})}><option value="square">Square gate</option><option value="sine">Sine gate</option></select></label><N label="Duration" value={duration} min={.1} max={3600} step={1} suffix="s" onChange={setDuration}/><label className="studio-field"><span>Sample rate</span><select value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="44100">44.1 kHz</option><option value="48000">48 kHz</option><option value="96000">96 kHz</option><option value="192000">192 kHz</option></select></label><div className="actions"><button onClick={()=>render()}>Validate signal</button><button className="primary small" onClick={exportWav}>Export lossless WAV</button></div>{diag&&<div className="technical"><b>{diag.present?'19.2 kHz carrier detected':'Carrier validation failed'}</b><span>L {diag.leftCarrierMagnitude.toFixed(4)} · R {diag.rightCarrierMagnitude.toFixed(4)} · confidence {Math.round(diag.confidence*100)}%</span></div>}</div>
 <div className="lab-card"><h3>Hardware bridges</h3><p>These capabilities are optional transport bridges; the 19.2 kHz audio file remains the compatibility artifact.</p><div className="chips"><span>Web MIDI: {(navigator as any).requestMIDIAccess?'available':'unavailable'}</span><span>Web Serial: {(navigator as any).serial?'available':'unavailable'}</span><span>Web Bluetooth: {(navigator as any).bluetooth?'available':'unavailable'}</span></div><button disabled={!(navigator as any).requestMIDIAccess} onClick={async()=>{try{const access=await (navigator as any).requestMIDIAccess();setMessage?.(`MIDI access granted · ${access.outputs.size} outputs.`)}catch(e){setMessage?.(String(e))}}}>Request MIDI access</button><button disabled={!(navigator as any).serial} onClick={async()=>{try{const port=await (navigator as any).serial.requestPort();setMessage?.(`Serial device selected: ${port.getInfo?JSON.stringify(port.getInfo()):'ready'}`)}catch(e){setMessage?.(String(e))}}}>Choose serial device</button><button disabled={!(navigator as any).bluetooth} onClick={async()=>{try{const d=await (navigator as any).bluetooth.requestDevice({acceptAllDevices:true});setMessage?.(`Bluetooth device selected: ${d.name||d.id}`)}catch(e){setMessage?.(String(e))}}}>Choose Bluetooth device</button></div>
 <div className="lab-card"><h3>Compatibility validation</h3><p>Legacy 19.2 kHz Light Control is validated in software for carrier frequency, envelope, duty cycle, phase, channel mapping and lossless export. Physical third-party decoder testing is not required for release.</p><div className="chips"><span>Software signal validation</span><span>Lossless reference export</span></div></div></div></section>}
