import {Preset,Project} from '../core/types.js';
import {deserializeSession} from '../core/sessionSchema.js';
import {PRESETS} from '../data/presets.js';
import {cloudConfigured,cloudFromStorage,CloudPreset} from '../cloud/supabase.js';
import {touchProject} from '../core/project.js';
import {PlaylistPanel} from './PlaylistPanel.js';
const collections=['all','research','curated','community','personal'] as const;
function row(p:Preset){const v=p.project.voices[0];return {type:v?.type||'—',ears:v?`${v.leftHz.toFixed(2)} / ${v.rightHz.toFixed(2)} Hz`:'—',beat:v?Math.abs(v.rightHz-v.leftHz).toFixed(2)+' Hz':'—',duration:Math.round(p.duration/60)+' min',voices:p.project.voices.length,automation:p.project.voices.reduce((n,v)=>n+v.automation.length,0),evidence:p.evidence.state,source:p.project.provenance.source||p.project.provenance.author};}
export function LibrarySurface({saved,project,setProject,setSurface,setMessage,onPlayPlaylist}:any){const [q,setQ]=React.useState(''),[collection,setCollection]=React.useState<(typeof collections)[number]>('all'),[evidence,setEvidence]=React.useState('all'),[compare,setCompare]=React.useState<string[]>([]),[cloud,setCloud]=React.useState<CloudPreset[]>([]),[loading,setLoading]=React.useState(false),[selectedCloud,setSelectedCloud]=React.useState<CloudPreset|null>(null),[rating,setRating]=React.useState(5),[review,setReview]=React.useState(''),[rights,setRights]=React.useState(false),[publishDesc,setPublishDesc]=React.useState(project.description||'');
 const refreshCloud=async()=>{if(!cloudConfigured()){setMessage?.('Configure Supabase in Settings to load community sessions.');return;}setLoading(true);try{setCloud(await cloudFromStorage().listPublicPresets(100));setMessage?.('Community library refreshed.')}catch(e){setMessage?.(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 React.useEffect(()=>{if(cloudConfigured())refreshCloud()},[]);
 const built=PRESETS.filter(p=>(collection==='all'||p.collection===collection)&& (evidence==='all'||p.evidence.state===evidence)&&(`${p.title} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase())));
 const local:Preset[]=saved.map((p:Project)=>({id:`local-${p.id}`,title:p.title,collection:'personal',description:p.description,duration:p.duration,purpose:'Personal',evidence:p.evidence,tags:p.tags,project:p}));
 const visibleLocal=(collection==='all'||collection==='personal')?local.filter(p=>(`${p.title} ${p.description}`).toLowerCase().includes(q.toLowerCase())):[];
 const allMap=new Map<string,Preset>([...PRESETS,...local].map(p=>[p.id,p]));const comparePresets=compare.map(id=>allMap.get(id)).filter(Boolean) as Preset[];
 const toggleCompare=(id:string)=>setCompare(x=>x.includes(id)?x.filter(i=>i!==id):x.length<2?[...x,id]:[x[1],id]);
 const open=(p:Project,source?:string)=>{const next=structuredClone(p);if(source){next.id=crypto.randomUUID();next.provenance={...next.provenance,source,lineage:[...(next.provenance.lineage||[]),source],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};next.revision=1;}setProject(next);setSurface('Studio')};
 const publish=async()=>{try{const res=await cloudFromStorage().publishPreset(project,{title:project.title,description:publishDesc,evidenceLevel:project.evidence.state,rightsDeclared:rights});setMessage?.(`Published ${Array.isArray(res)?res[0]?.title||project.title:project.title}.`);setRights(false);await refreshCloud()}catch(e){setMessage?.(e instanceof Error?e.message:String(e))}};
 const submitReview=async()=>{if(!selectedCloud)return;try{await cloudFromStorage().review(selectedCloud.id,rating,review);setMessage?.('Review saved.');setReview('')}catch(e){setMessage?.(e instanceof Error?e.message:String(e))}};
 return <section className="page"><div className="eyebrow">LIBRARY</div><h1>Research, curated, community, and yours</h1><div className="library-toolbar"><input className="search" placeholder="Search title, tags, description" value={q} onChange={e=>setQ(e.target.value)}/><select value={evidence} onChange={e=>setEvidence(e.target.value)}><option value="all">All evidence</option>{Array.from(new Set(PRESETS.map(p=>p.evidence.state))).map(x=><option key={x}>{x}</option>)}</select><button onClick={refreshCloud} disabled={loading}>{loading?'Loading…':'Refresh community'}</button></div><div className="tabs">{collections.map(c=><button key={c} className={collection===c?'active':''} onClick={()=>setCollection(c)}>{c[0].toUpperCase()+c.slice(1)}</button>)}</div>
 {comparePresets.length>0&&<div className="compare-panel"><div className="compare-head"><h3>Preset comparison</h3><button onClick={()=>setCompare([])}>Clear</button></div><table><thead><tr><th>Attribute</th>{comparePresets.map(p=><th key={p.id}>{p.title}</th>)}</tr></thead><tbody>{(['type','ears','beat','duration','voices','automation','evidence','source'] as const).map(k=><tr key={k}><th>{k}</th>{comparePresets.map(p=><td key={p.id}>{String(row(p)[k])}</td>)}</tr>)}</tbody></table><small>Select a preset and open it to copy individual tracks/envelopes in Studio. Opening a built-in/community item creates an editable local fork.</small></div>}
 {visibleLocal.length>0&&<><h2>My Library</h2><div className="card-grid compact">{visibleLocal.map(p=><article className="preset" key={p.id}><div><span className="collection">personal</span><h3>{p.title}</h3><p>{p.description}</p><small>Revision {p.project.revision}</small></div><div className="actions"><button onClick={()=>toggleCompare(p.id)}>{compare.includes(p.id)?'Compared ✓':'Compare'}</button><button className="primary small" onClick={()=>open(p.project)}>Open</button></div></article>)}</div></>}
 {(collection==='all'||collection==='research'||collection==='curated')&&<><h2>Built in · {built.length}</h2><div className="card-grid compact">{built.map(p=><article className="preset" key={p.id}><div><div className="preset-meta"><span className="collection">{p.collection}</span><span className="evidence-tag">{p.evidence.state}</span></div><h3>{p.title}</h3><p>{p.description}</p><small>{row(p).ears} · Δ {row(p).beat} · {row(p).duration}</small></div><div className="actions"><button onClick={()=>toggleCompare(p.id)}>{compare.includes(p.id)?'Compared ✓':'Compare'}</button><button className="primary small" onClick={()=>open(p.project,`builtin:${p.id}`)}>Open fork</button></div></article>)}</div></>}
 {(collection==='all'||collection==='community')&&<><div className="section-head"><h2>Community · {cloud.length}</h2><small>Community claims are user-submitted and are not scientific validation.</small></div>{cloud.length?<div className="card-grid compact">{cloud.filter(p=>(`${p.title} ${p.description}`).toLowerCase().includes(q.toLowerCase())).map(p=><article className="preset" key={p.id}><div><div className="preset-meta"><span className="collection">community</span><span className="evidence-tag">{p.evidence_level||'community-claim'}</span></div><h3>{p.title}</h3><p>{p.description}</p></div><div className="actions"><button onClick={()=>setSelectedCloud(p)}>Review</button><button onClick={async()=>{try{await cloudFromStorage().favorite(p.id);setMessage?.('Added to favorites.')}catch(e){setMessage?.(String(e))}}}>♡ Favorite</button><button className="primary small" onClick={()=>open(deserializeSession(p.session),`community:${p.id}`)}>Open fork</button></div></article>)}</div>:<div className="empty-state"><b>{cloudConfigured()?'No community sessions returned.':'Cloud not configured.'}</b><p>{cloudConfigured()?'Publish a session or refresh the library.':'Local and built-in libraries remain fully functional without an account.'}</p></div>}</>}
 <div className="publish-card"><h2>Publish current session</h2><p>Publishing requires a verified account and a rights declaration. Imported commercial audio cannot be redistributed without permission.</p><label>Description<textarea value={publishDesc} onChange={e=>setPublishDesc(e.target.value)}/></label><label><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/> I have redistribution rights for every embedded/public asset in this session.</label><button className="primary" disabled={!rights} onClick={publish}>Publish to community</button></div>
 <PlaylistPanel current={project} onPlay={onPlayPlaylist} setMessage={setMessage}/>{selectedCloud&&<div className="modal-backdrop" onClick={()=>setSelectedCloud(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><h3>Review {selectedCloud.title}</h3><label>Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} / 5</option>)}</select></label><label>Review<textarea value={review} onChange={e=>setReview(e.target.value)}/></label><div className="actions"><button className="primary small" onClick={submitReview}>Save review</button><button onClick={async()=>{const why=prompt('Why are you reporting this preset?');if(!why)return;try{await cloudFromStorage().report('preset',selectedCloud.id,why);setMessage?.('Report submitted.');setSelectedCloud(null)}catch(e){setMessage?.(String(e))}}}>Report</button><button onClick={()=>setSelectedCloud(null)}>Close</button></div></div></div>}</section>}
