import {AnalysisResult,Project,StereoBuffer,SpectrumResult} from '../core/types.js';
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function stats(buf:StereoBuffer){let pl=0,pr=0,sl=0,sr=0,xy=0,x2=0,y2=0,dl=0,dr=0,diff2=0;for(let i=0;i<buf.left.length;i++){const l=buf.left[i],r=buf.right[i];pl=Math.max(pl,Math.abs(l));pr=Math.max(pr,Math.abs(r));sl+=l*l;sr+=r*r;xy+=l*r;x2+=l*l;y2+=r*r;dl+=l;dr+=r;const d=l-r;diff2+=d*d;}const n=Math.max(1,buf.left.length),rmsL=Math.sqrt(sl/n),rmsR=Math.sqrt(sr/n),diffRms=Math.sqrt(diff2/n);return {peakLeft:pl,peakRight:pr,rmsLeft:rmsL,rmsRight:rmsR,correlation:xy/Math.sqrt(Math.max(1e-20,x2*y2)),clipping:pl>=.999999||pr>=.999999,dcLeft:dl/n,dcRight:dr/n,mono:diffRms<Math.max(1e-7,(rmsL+rmsR)*.0001),channelUnique:diffRms>=Math.max(1e-7,(rmsL+rmsR)*.0001)};}
export function goertzel(samples:Float32Array,sampleRate:number,freq:number){if(freq<=0||freq>=sampleRate/2)return 0;const w=2*Math.PI*freq/sampleRate,c=2*Math.cos(w);let s0=0,s1=0,s2=0;for(let i=0;i<samples.length;i++){s0=samples[i]+c*s1-s2;s2=s1;s1=s0;}return Math.sqrt(Math.max(0,s1*s1+s2*s2-c*s1*s2))/Math.max(1,samples.length);}
export function dominantFrequency(samples:Float32Array,sampleRate:number,minHz=20,maxHz=1400){const n=Math.min(samples.length,Math.max(4096,Math.floor(sampleRate*2))),src=samples.subarray(0,n);let best=0,bestMag=-1;const resolution=sampleRate/n,lo=Math.max(1,Math.floor(minHz/resolution)),hi=Math.min(Math.floor(maxHz/resolution),Math.floor(n/2)-1);for(let k=lo;k<=hi;k++){const f=k*resolution,m=goertzel(src,sampleRate,f);if(m>bestMag){bestMag=m;best=f;}}return best;}
export function cpuSpectrum(samples:Float32Array,sampleRate:number,bins=512):SpectrumResult{const n=Math.min(samples.length,4096),src=samples.subarray(0,n),freqs=new Float32Array(bins),mags=new Float32Array(bins),max=sampleRate/2;for(let i=0;i<bins;i++){const f=(i+1)*max/(bins+1);freqs[i]=f;mags[i]=goertzel(src,sampleRate,f);}return {frequencies:freqs,magnitudes:mags,backend:'cpu'};}
export interface SpectrogramResult{times:Float32Array;frequencies:Float32Array;magnitudes:Float32Array;frames:number;bins:number;backend:'webgpu'|'cpu';}
export function cpuSpectrogram(samples:Float32Array,sampleRate:number,bins=96,windowSize=2048,hop=512):SpectrogramResult{windowSize=Math.max(128,Math.min(windowSize,samples.length||128));hop=Math.max(1,hop);const frames=Math.max(1,1+Math.floor(Math.max(0,samples.length-windowSize)/hop)),times=new Float32Array(frames),freqs=new Float32Array(bins),out=new Float32Array(frames*bins);for(let b=0;b<bins;b++)freqs[b]=(b+1)*(sampleRate*.5)/(bins+1);for(let f=0;f<frames;f++){const start=Math.min(f*hop,Math.max(0,samples.length-windowSize)),win=samples.subarray(start,start+windowSize);times[f]=(start+windowSize/2)/sampleRate;for(let b=0;b<bins;b++)out[f*bins+b]=goertzel(win,sampleRate,freqs[b]);}return {times,frequencies:freqs,magnitudes:out,frames,bins,backend:'cpu'};}
function topPeaks(samples:Float32Array,sr:number,min=40,max=1200,count=6){const n=Math.min(samples.length,Math.max(4096,Math.floor(sr*2))),res=sr/n,candidates:Array<{f:number;m:number}>=[];for(let k=Math.max(1,Math.floor(min/res));k<=Math.min(Math.floor(max/res),Math.floor(n/2)-1);k++){const f=k*res,m=goertzel(samples.subarray(0,n),sr,f);if(candidates.length<count||m>candidates[candidates.length-1].m){candidates.push({f,m});candidates.sort((a,b)=>b.m-a.m);candidates.length=Math.min(count,candidates.length);}}return candidates;}
export function analyzeStereo(buf:StereoBuffer):AnalysisResult{const st=stats(buf),dl=dominantFrequency(buf.left,buf.sampleRate),dr=dominantFrequency(buf.right,buf.sampleRate),diff=Math.abs(dr-dl),ownL=goertzel(buf.left,buf.sampleRate,dl),ownR=goertzel(buf.right,buf.sampleRate,dr),crossL=goertzel(buf.left,buf.sampleRate,dr),crossR=goertzel(buf.right,buf.sampleRate,dl),leak=Math.max(crossL/Math.max(1e-12,ownL),crossR/Math.max(1e-12,ownR)),leakageDb=20*Math.log10(Math.max(1e-12,leak));const purity=Math.max(ownL,ownR),confidence=clamp(purity*8*(1-Math.abs(st.correlation)*.2)*(st.mono?.2:1),0,1),lp=topPeaks(buf.left,buf.sampleRate),rp=topPeaks(buf.right,buf.sampleRate),candidates:Array<{leftHz:number;rightHz:number;differenceHz:number;score:number}>=[];for(const l of lp)for(const r of rp){const d=Math.abs(r.f-l.f);if(d<=100)candidates.push({leftHz:l.f,rightHz:r.f,differenceHz:d,score:l.m*r.m});}candidates.sort((a,b)=>b.score-a.score);candidates.length=Math.min(8,candidates.length);const issues:string[]=[];if(st.mono)issues.push('Channels are effectively mono/identical.');if(st.clipping)issues.push('Digital clipping detected.');if(Math.abs(st.dcLeft)>0.01||Math.abs(st.dcRight)>0.01)issues.push('Material DC offset detected.');if(diff<.05||diff>100)issues.push('No conventional binaural carrier difference was identified.');return {...st,duration:buf.duration,sampleRate:buf.sampleRate,dominantLeftHz:dl,dominantRightHz:dr,differenceHz:diff,leakageDb,confidence,classification:!st.mono&&diff>.05&&diff<100?'Consistent with a stereo carrier pair':'No clear binaural carrier pair detected',candidates,integrityIssues:issues,backend:'cpu',spectrum:cpuSpectrum(buf.left,buf.sampleRate)};}
export function compareAgainstProject(buf:StereoBuffer,project:Project,toleranceHz=.75){const issues:string[]=[];const a=analyzeStereo(buf),v=project.voices.find(x=>x.type==='binaural'&&!x.mute);if(a.clipping)issues.push('clipping');if(a.mono)issues.push('mono-summed');if(v){const direct=v.automation.some(x=>['leftHz','rightHz','beatHz','carrierHz'].includes(x.parameter));if(!direct){if(Math.abs(a.dominantLeftHz-v.leftHz)>toleranceHz)issues.push('left-carrier-mismatch');if(Math.abs(a.dominantRightHz-v.rightHz)>toleranceHz)issues.push('right-carrier-mismatch');if(Math.abs(a.dominantLeftHz-v.rightHz)<=toleranceHz&&Math.abs(a.dominantRightHz-v.leftHz)<=toleranceHz)issues.push('channels-swapped');}}return {pass:issues.length===0,issues,analysis:a};}
