import {Project,StereoBuffer} from '../core/types.js';
export class LiveEngine{
 private ctx:AudioContext|null=null;private node:AudioWorkletNode|null=null;private fallback=false;private leftOsc:OscillatorNode|null=null;private rightOsc:OscillatorNode|null=null;private leftGain:GainNode|null=null;private rightGain:GainNode|null=null;private merger:ChannelMergerNode|null=null;private ended:()=>void=()=>{};
 async init(){if(this.ctx)return;this.ctx=new AudioContext();try{await this.ctx.audioWorklet.addModule('./public/worklet.js');this.node=new AudioWorkletNode(this.ctx,'binaural-studio',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2]});this.node.channelCount=2;this.node.channelCountMode='explicit';this.node.channelInterpretation='discrete';this.node.port.onmessage=(e)=>{if(e.data?.type==='ended')this.ended();};this.node.connect(this.ctx.destination);}catch{this.fallback=true;}}
 private setupFallback(project:Project){const v=project.voices[0];if(!v||!this.ctx)return;this.leftOsc=this.ctx.createOscillator();this.rightOsc=this.ctx.createOscillator();this.leftGain=this.ctx.createGain();this.rightGain=this.ctx.createGain();this.merger=this.ctx.createChannelMerger(2);this.leftOsc.frequency.value=v.leftHz;this.rightOsc.frequency.value=v.rightHz;this.leftGain.gain.value=project.masterGain*v.amplitude*v.leftLevel;this.rightGain.gain.value=project.masterGain*v.amplitude*v.rightLevel;this.leftOsc.connect(this.leftGain).connect(this.merger,0,0);this.rightOsc.connect(this.rightGain).connect(this.merger,0,1);this.merger.connect(this.ctx.destination);this.leftOsc.start();this.rightOsc.start();}
 async start(project:Project,position=0,onEnded?:()=>void,assets:Record<string,StereoBuffer>={}){if(position!==0)throw new Error('Non-zero live seek is not enabled until exact phase/noise state transfer is available.');await this.init();if(onEnded)this.ended=onEnded;await this.ctx!.resume();if(this.fallback){this.setupFallback(project);return;}this.node!.port.postMessage({type:'project',project:structuredClone(project),assets});this.node!.port.postMessage({type:'start',position:0});}
 update(project:Project,assets:Record<string,StereoBuffer>={}){if(this.fallback){const v=project.voices[0];if(v&&this.leftOsc&&this.rightOsc&&this.leftGain&&this.rightGain){this.leftOsc.frequency.value=v.leftHz;this.rightOsc.frequency.value=v.rightHz;this.leftGain.gain.value=project.masterGain*v.amplitude*v.leftLevel;this.rightGain.gain.value=project.masterGain*v.amplitude*v.rightLevel;}return;}this.node?.port.postMessage({type:'project',project:structuredClone(project),assets});}
 stop(){if(this.fallback){try{this.leftOsc?.stop();this.rightOsc?.stop();}catch{}this.leftOsc?.disconnect();this.rightOsc?.disconnect();this.merger?.disconnect();this.leftOsc=this.rightOsc=null;return;}this.node?.port.postMessage({type:'stop'});}get sampleRate(){return this.ctx?.sampleRate??0;}
}
