import {NoiseTrack} from '../core/types.js';
import {clamp,trackParameterValue} from './signalMath.js';

export interface NoiseColorState{seed:number;pink0:number;pink1:number;pink2:number;brown:number;prev1:number;prev2:number;lpHigh:number;lpLow:number;}
export interface NoiseRuntimeState{left:NoiseColorState;right:NoiseColorState;shared:NoiseColorState;}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h|0;}
function channel(seed:number):NoiseColorState{return {seed:seed||1,pink0:0,pink1:0,pink2:0,brown:0,prev1:0,prev2:0,lpHigh:0,lpLow:0};}
export function createNoiseState(trackId:string,seed=0x51a7c0de):NoiseRuntimeState{const h=hash(trackId);return {left:channel(seed^h^0x1f123bb5),right:channel(seed^h^0x5f356495),shared:channel(seed^h^0x13579bdf)};}
function rng(s:NoiseColorState){let x=s.seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.seed=x|0;return ((x>>>0)/4294967295)*2-1;}
function baseKinds(s:NoiseColorState){const w=rng(s);s.pink0=.99765*s.pink0+w*.099046;s.pink1=.963*s.pink1+w*.2965164;s.pink2=.57*s.pink2+w*1.0526913;const pink=(s.pink0+s.pink1+s.pink2+w*.1848)*.18;s.brown=clamp((s.brown+.02*w)/1.02,-1,1);const brown=s.brown*3.5,blue=clamp((w-s.prev1)*.7,-1,1),violet=clamp((w-2*s.prev1+s.prev2)*.35,-1,1);s.prev2=s.prev1;s.prev1=w;const grey=.7*w+.3*Math.sign(w)*Math.sqrt(Math.abs(w));return {white:w,pink,brown,blue,violet,grey};}
function color(track:NoiseTrack,s:NoiseColorState,slopeOverride?:number){const k=baseKinds(s);if(track.kind==='slope'){const x=clamp(slopeOverride??track.slopeDbOct,-6,6);if(x<=-3){const t=(x+6)/3;return k.brown*(1-t)+k.pink*t;}if(x<=0){const t=(x+3)/3;return k.pink*(1-t)+k.white*t;}if(x<=3){const t=x/3;return k.white*(1-t)+k.blue*t;}const t=(x-3)/3;return k.blue*(1-t)+k.violet*t;}return k[track.kind]??k.white;}
function filter(track:NoiseTrack,s:NoiseColorState,x:number,sr:number,highpass=track.highpass||0,lowpass=track.lowpass||0){let y=x;if(highpass>0){const a=1-Math.exp(-2*Math.PI*Math.min(highpass,sr*.45)/sr);s.lpHigh+=a*(y-s.lpHigh);y-=s.lpHigh;}if(lowpass>0){const a=1-Math.exp(-2*Math.PI*Math.min(lowpass,sr*.45)/sr);s.lpLow+=a*(y-s.lpLow);y=s.lpLow;}return y;}
export function nextNoiseStereo(track:NoiseTrack,state:NoiseRuntimeState,sampleRate:number,out:Float64Array,time=0){const amp=trackParameterValue(track.automation,'amplitude',time,track.amplitude,track.modulation),slope=trackParameterValue(track.automation,'slopeDbOct',time,track.slopeDbOct,track.modulation),hp=trackParameterValue(track.automation,'highpass',time,track.highpass||0,track.modulation),lp=trackParameterValue(track.automation,'lowpass',time,track.lowpass||0,track.modulation),corr=trackParameterValue(track.automation,'stereoCorrelation',time,track.stereoCorrelation,track.modulation);const a=color(track,state.left,slope),b=color(track,state.right,slope),shared=color(track,state.shared,slope),c=clamp(corr,0,1),s=Math.sqrt(c),i=Math.sqrt(1-c);out[0]=filter(track,state.left,a*i+shared*s,sampleRate,hp,lp)*amp;out[1]=filter(track,state.right,b*i+shared*s,sampleRate,hp,lp)*amp;}
