import {Project,StereoBuffer,Voice} from '../core/types.js';
import {clamp,createModulationRuntime,envelope,ModulationRuntime,phaseStep,resolveVoiceFrame,TAU,waveformSample,advancedWaveformSample,deterministicNoise,segmentContext,waveformAt} from './signalMath.js';
import {createNoiseState,nextNoiseStereo,NoiseRuntimeState} from './noise.js';
import {audioTrackSample,createAudioTrackRuntime,AudioTrackRuntime} from './audioTrackMath.js';

export interface RenderOptions{sampleRate?:number;start?:number;duration?:number;seed?:number;assets?:Record<string,StereoBuffer>;onProgress?:(p:number)=>void;}
interface RenderState{phaseL:Map<string,number>;phaseR:Map<string,number>;noise:Map<string,NoiseRuntimeState>;links:Map<string,ModulationRuntime>;audio:Map<string,AudioTrackRuntime>;}
function activeVoice(v:Voice,t:number){if(v.mute||t<v.start)return null;const span=Math.max(1e-9,v.duration),rel=t-v.start,total=v.loop?Infinity:span*Math.max(1,v.repetitions);if(rel>=total)return null;return rel%span;}

export class ProjectRenderer{
 readonly sampleRate:number;private state:RenderState={phaseL:new Map(),phaseR:new Map(),noise:new Map(),links:new Map(),audio:new Map()};private frame=0;private noiseTmp=new Float64Array(2);private audioTmp=new Float64Array(2);private seed:number;private anySolo:boolean;
 constructor(readonly project:Project,readonly assets:Record<string,StereoBuffer>={},sampleRate=project.sampleRate,seed=0x51a7c0de){this.sampleRate=sampleRate;this.seed=seed;this.anySolo=project.voices.some(v=>v.solo)||project.noiseTracks.some(n=>n.solo)||project.audioTracks.some(a=>a.solo);}
 get positionSeconds(){return this.frame/this.sampleRate;}
 reset(){this.frame=0;this.state={phaseL:new Map(),phaseR:new Map(),noise:new Map(),links:new Map(),audio:new Map()};}
 advanceTo(seconds:number){const target=Math.max(0,Math.round(seconds*this.sampleRate));if(target<this.frame)this.reset();const scratch=4096;while(this.frame<target)this.renderFrames(Math.min(scratch,target-this.frame),false);}
 renderFrames(count:number,capture=true):StereoBuffer{count=Math.max(0,Math.floor(count));const left=new Float32Array(capture?count:0),right=new Float32Array(capture?count:0);for(let oi=0;oi<count;oi++){const t=this.frame/this.sampleRate;let l=0,r=0;
  for(const v of this.project.voices){if(this.anySolo&&!v.solo)continue;const sc=segmentContext(this.project,v.id,t);if(!sc)continue;const local=activeVoice(v,sc.time);if(local===null)continue;let mr=this.state.links.get(v.id);if(!mr){mr=createModulationRuntime();this.state.links.set(v.id,mr);}const fp=resolveVoiceFrame(v,local,mr,1/this.sampleRate);if(sc.overrides){if(Number.isFinite(sc.overrides.carrierHz)){const b=fp.beatHz;fp.leftHz=Number(sc.overrides.carrierHz)-b/2;fp.rightHz=Number(sc.overrides.carrierHz)+b/2;}if(Number.isFinite(sc.overrides.beatHz)){const c=(fp.leftHz+fp.rightHz)/2,b=Math.abs(Number(sc.overrides.beatHz));fp.leftHz=c-b/2;fp.rightHz=c+b/2;}if(Number.isFinite(sc.overrides.amplitude))fp.amplitude=Number(sc.overrides.amplitude);if(Number.isFinite(sc.overrides.pan))fp.pan=Number(sc.overrides.pan);if(Number.isFinite(sc.overrides.duty))fp.duty=Number(sc.overrides.duty);}let fl=fp.leftHz,fr=fp.rightHz;const amp=fp.amplitude*envelope(v,local)*sc.gain;let pl=this.state.phaseL.get(v.id)??v.phaseLeft,pr=this.state.phaseR.get(v.id)??v.phaseRight;const duty=fp.duty,pan=fp.pan,cycle=v.cycleAssetId?this.assets[v.cycleAssetId]?.left:undefined,sampleL=()=>advancedWaveformSample(waveformAt(v,local),pl,duty,fl,this.sampleRate,v.harmonics,cycle),sampleR=()=>advancedWaveformSample(waveformAt(v,local),pr,duty,fr,this.sampleRate,v.harmonics,cycle),panL=Math.cos((pan+1)*Math.PI/4)*Math.SQRT2,panR=Math.sin((pan+1)*Math.PI/4)*Math.SQRT2;if(v.type==='monaural'){const a=sampleL(),b=sampleR(),m=(a+b)*.5*amp;l+=m*v.leftLevel*panL;r+=m*v.rightLevel*panR;}else if(v.type==='isochronic'){const carrier=(fl+fr)/2,mod=Math.abs(fr-fl),gate=((t*mod)%1)<duty?1:0,s=sampleL()*amp*gate;l+=s*v.leftLevel*panL;r+=s*v.rightLevel*panR;fl=fr=carrier;}else if(v.type==='am'){const carrier=(fl+fr)/2,mod=Math.abs(fr-fl),m=.5+.5*Math.sin(TAU*mod*t),s=sampleL()*amp*m;l+=s*v.leftLevel*panL;r+=s*v.rightLevel*panR;fl=fr=carrier;}else if(v.type==='sham'){const carrier=(fl+fr)/2,s=sampleL()*amp;l+=s*v.leftLevel*panL;r+=s*v.rightLevel*panR;fl=fr=carrier;}else if(v.type==='noise-modulated'){const carrier=(fl+fr)/2,depth=clamp(duty,0,1),nm=1-depth+depth*(deterministicNoise(v.id,this.frame)*.5+.5),sl=sampleL()*amp*nm,sr=sampleR()*amp*nm;l+=sl*v.leftLevel*panL;r+=sr*v.rightLevel*panR;fl=fr=carrier;}else{l+=sampleL()*amp*v.leftLevel*panL;r+=sampleR()*amp*v.rightLevel*panR;}pl=(pl+phaseStep(fl,this.sampleRate))%TAU;pr=(pr+phaseStep(fr,this.sampleRate))%TAU;this.state.phaseL.set(v.id,pl);this.state.phaseR.set(v.id,pr);}
  for(const n of this.project.noiseTracks){const sc=segmentContext(this.project,n.id,t);if(!sc||n.mute||(this.anySolo&&!n.solo)||sc.time<n.start||(!n.loop&&sc.time>=n.start+n.duration))continue;let ns=this.state.noise.get(n.id);if(!ns){ns=createNoiseState(n.id,this.seed);this.state.noise.set(n.id,ns);}nextNoiseStereo(n,ns,this.sampleRate,this.noiseTmp,sc.time-n.start);l+=this.noiseTmp[0];r+=this.noiseTmp[1];}
  for(const a of this.project.audioTracks){const sc=segmentContext(this.project,a.id,t);if(!sc||a.mute||(this.anySolo&&!a.solo)||sc.time<a.start)continue;const src=this.assets[a.assetId];if(!src)continue;let ar=this.state.audio.get(a.id);if(!ar){ar=createAudioTrackRuntime();this.state.audio.set(a.id,ar);}if(audioTrackSample(a,src,sc.time,this.audioTmp,ar,this.sampleRate)){l+=this.audioTmp[0]*sc.gain;r+=this.audioTmp[1]*sc.gain;}}
  if(capture){left[oi]=l*this.project.masterGain;right[oi]=r*this.project.masterGain;}this.frame++;}
 return {sampleRate:this.sampleRate,left,right,duration:count/this.sampleRate};}
}
export function renderProject(project:Project,options:RenderOptions={}):StereoBuffer{const sr=options.sampleRate??project.sampleRate,start=Math.max(0,options.start??0),dur=Math.max(0,Math.min(options.duration??project.duration-start,project.duration-start)),frames=Math.max(0,Math.round(dur*sr)),renderer=new ProjectRenderer(project,options.assets||{},sr,options.seed);renderer.advanceTo(start);const chunk=renderer.renderFrames(frames);options.onProgress?.(1);return chunk;}
export function* renderProjectChunks(project:Project,chunkSeconds=10,options:Omit<RenderOptions,'start'|'duration'>={}){const sr=options.sampleRate??project.sampleRate,renderer=new ProjectRenderer(project,options.assets||{},sr,options.seed),chunkFrames=Math.max(1,Math.round(chunkSeconds*sr)),total=Math.round(project.duration*sr);let done=0;while(done<total){const n=Math.min(chunkFrames,total-done);yield renderer.renderFrames(n);done+=n;options.onProgress?.(done/total);}}
