import {Project,StereoBuffer,Voice} from '../core/types.js';
import {createModulationRuntime,envelope,ModulationRuntime,phaseStep,resolveVoiceFrame,TAU,waveformSample,advancedWaveformSample,deterministicNoise,segmentContext,waveformAt} from './signalMath.js';
import {createNoiseState,nextNoiseStereo,NoiseRuntimeState} from './noise.js';
import {audioTrackSample,createAudioTrackRuntime,AudioTrackRuntime} from './audioTrackMath.js';
type VoiceState={id:string;phaseL:number;phaseR:number;mod:ModulationRuntime};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function active(v:Voice,t:number){if(v.mute||t<v.start)return -1;const span=Math.max(1e-9,v.duration),rel=t-v.start,total=v.loop?Infinity:span*Math.max(1,v.repetitions);return rel>=total?-1:rel%span;}
class BinauralProcessor extends AudioWorkletProcessor{
 private project:Project|null=null;private voices:VoiceState[]=[];private noises:NoiseRuntimeState[]=[];private assets:Record<string,StereoBuffer>={};private noiseTmp=new Float64Array(2);private audioTmp=new Float64Array(2);private active=false;private position=0;private audioRuntime=new Map<string,AudioTrackRuntime>();
 constructor(){super();this.port.onmessage=(e:any)=>{const d=e.data||{};if(d.type==='project'){const old=this.voices;this.project=d.project as Project;this.assets=d.assets||{};this.voices=this.project.voices.map((v:Voice)=>{const x=old.find(s=>s.id===v.id);return x||{id:v.id,phaseL:v.phaseLeft,phaseR:v.phaseRight,mod:createModulationRuntime()};});this.noises=this.project.noiseTracks.map(n=>createNoiseState(n.id));this.audioRuntime.clear();}if(d.type==='start'){if(Number.isFinite(d.position))this.position=Math.max(0,d.position);this.active=true;}if(d.type==='stop')this.active=false;if(d.type==='reset'){this.position=0;this.active=false;this.resetPhases();}};}
 private resetPhases(){const p=this.project;if(!p)return;for(let i=0;i<this.voices.length;i++){this.voices[i].phaseL=p.voices[i]?.phaseLeft||0;this.voices[i].phaseR=p.voices[i]?.phaseRight||0;this.voices[i].mod=createModulationRuntime();}this.noises=p.noiseTracks.map(n=>createNoiseState(n.id));this.audioRuntime.clear();}
 process(_inputs:any[],outputs:any[]){const out=outputs[0];if(!out?.[0])return true;const l=out[0],r=out[1]||out[0],p=this.project;if(!p||!this.active){l.fill(0);if(r!==l)r.fill(0);return true;}const anySolo=p.voices.some(v=>v.solo)||p.noiseTracks.some(n=>n.solo)||p.audioTracks.some(a=>a.solo);for(let i=0;i<l.length;i++){const t=this.position;let lv=0,rv=0;for(let vi=0;vi<p.voices.length;vi++){const v=p.voices[vi];if(anySolo&&!v.solo)continue;const sc=segmentContext(p,v.id,t);if(!sc)continue;const local=active(v,sc.time);if(local<0)continue;const st=this.voices[vi],fp=resolveVoiceFrame(v,local,st.mod,1/sampleRate);if(sc.overrides){if(Number.isFinite(sc.overrides.carrierHz)){const b=fp.beatHz;fp.leftHz=Number(sc.overrides.carrierHz)-b/2;fp.rightHz=Number(sc.overrides.carrierHz)+b/2;}if(Number.isFinite(sc.overrides.beatHz)){const c=(fp.leftHz+fp.rightHz)/2,b=Math.abs(Number(sc.overrides.beatHz));fp.leftHz=c-b/2;fp.rightHz=c+b/2;}if(Number.isFinite(sc.overrides.amplitude))fp.amplitude=Number(sc.overrides.amplitude);if(Number.isFinite(sc.overrides.pan))fp.pan=Number(sc.overrides.pan);if(Number.isFinite(sc.overrides.duty))fp.duty=Number(sc.overrides.duty);}let fl=fp.leftHz,fr=fp.rightHz;const amp=fp.amplitude*envelope(v,local)*sc.gain,duty=fp.duty,pan=fp.pan,cycle=v.cycleAssetId?this.assets[v.cycleAssetId]?.left:undefined,sampleL=()=>advancedWaveformSample(waveformAt(v,local),st.phaseL,duty,fl,sampleRate,v.harmonics,cycle),sampleR=()=>advancedWaveformSample(waveformAt(v,local),st.phaseR,duty,fr,sampleRate,v.harmonics,cycle),panL=Math.cos((pan+1)*Math.PI/4)*Math.SQRT2,panR=Math.sin((pan+1)*Math.PI/4)*Math.SQRT2;if(v.type==='monaural'){const a=sampleL(),b=sampleR(),m=(a+b)*.5*amp;lv+=m*v.leftLevel*panL;rv+=m*v.rightLevel*panR;}else if(v.type==='isochronic'){const carrier=(fl+fr)/2,mod=Math.abs(fr-fl),gate=((t*mod)%1)<duty?1:0,s=sampleL()*amp*gate;lv+=s*v.leftLevel*panL;rv+=s*v.rightLevel*panR;fl=fr=carrier;}else if(v.type==='am'){const carrier=(fl+fr)/2,mod=Math.abs(fr-fl),m=.5+.5*Math.sin(TAU*mod*t),s=sampleL()*amp*m;lv+=s*v.leftLevel*panL;rv+=s*v.rightLevel*panR;fl=fr=carrier;}else if(v.type==='sham'){const carrier=(fl+fr)/2,s=sampleL()*amp;lv+=s*v.leftLevel*panL;rv+=s*v.rightLevel*panR;fl=fr=carrier;}else if(v.type==='noise-modulated'){const carrier=(fl+fr)/2,depth=clamp(duty,0,1),frame=Math.floor(t*sampleRate),nm=1-depth+depth*(deterministicNoise(v.id,frame)*.5+.5);lv+=sampleL()*amp*nm*v.leftLevel*panL;rv+=sampleR()*amp*nm*v.rightLevel*panR;fl=fr=carrier;}else{lv+=sampleL()*amp*v.leftLevel*panL;rv+=sampleR()*amp*v.rightLevel*panR;}st.phaseL=(st.phaseL+phaseStep(fl,sampleRate))%TAU;st.phaseR=(st.phaseR+phaseStep(fr,sampleRate))%TAU;}
 for(let ni=0;ni<p.noiseTracks.length;ni++){const n=p.noiseTracks[ni];const sc=segmentContext(p,n.id,t);if(!sc||n.mute||(anySolo&&!n.solo)||sc.time<n.start||(!n.loop&&sc.time>=n.start+n.duration))continue;nextNoiseStereo(n,this.noises[ni],sampleRate,this.noiseTmp,sc.time-n.start);lv+=this.noiseTmp[0];rv+=this.noiseTmp[1];}
 for(const a of p.audioTracks){const sc=segmentContext(p,a.id,t);if(!sc||a.mute||(anySolo&&!a.solo))continue;const src=this.assets[a.assetId];if(src){let ar=this.audioRuntime.get(a.id);if(!ar){ar=createAudioTrackRuntime();this.audioRuntime.set(a.id,ar);}if(audioTrackSample(a,src,sc.time,this.audioTmp,ar,sampleRate)){lv+=this.audioTmp[0]*sc.gain;rv+=this.audioTmp[1]*sc.gain;}}}
 l[i]=clamp(lv*p.masterGain,-1,1);r[i]=clamp(rv*p.masterGain,-1,1);this.position+=1/sampleRate;if(this.position>=p.duration){this.active=false;this.port.postMessage({type:'ended'});}}
 return true;}
}
registerProcessor('binaural-studio',BinauralProcessor);
