import {StereoBuffer} from '../core/types.js';
const MAX_AIFF_FRAMES=96_000_000;
function put(v:DataView,o:number,s:string){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));}
function tag(bytes:Uint8Array,o:number){return String.fromCharCode(...bytes.slice(o,o+4));}
function ext80(rate:number){const exp=Math.floor(Math.log2(rate)),frac=rate/Math.pow(2,exp),e=exp+16383;return {e,hi:Math.floor(frac*Math.pow(2,31)),lo:Math.floor((frac*Math.pow(2,63))%Math.pow(2,32))};}
function readExt80(v:DataView,o:number){const e=v.getUint16(o,false);if(e===0)return 0;const hi=v.getUint32(o+2,false),lo=v.getUint32(o+6,false),frac=hi/Math.pow(2,31)+lo/Math.pow(2,63);return frac*Math.pow(2,e-16383);}

export function encodeAiff(buf:StereoBuffer,bits:16|24|32=24){
 if(buf.left.length!==buf.right.length)throw new Error('AIFF requires equal stereo channel lengths');if(!Number.isSafeInteger(buf.sampleRate)||buf.sampleRate<1||buf.sampleRate>768000)throw new Error('Invalid AIFF sample rate');const bytes=bits/8,frames=buf.left.length,dataBytes=frames*2*bytes;if(dataBytes>0xffffffff-46)throw new Error('AIFF exceeds container size limit');const ab=new ArrayBuffer(54+dataBytes),v=new DataView(ab);put(v,0,'FORM');v.setUint32(4,46+dataBytes,false);put(v,8,'AIFF');put(v,12,'COMM');v.setUint32(16,18,false);v.setUint16(20,2,false);v.setUint32(22,frames,false);v.setUint16(26,bits,false);const x=ext80(buf.sampleRate);v.setUint16(28,x.e,false);v.setUint32(30,x.hi,false);v.setUint32(34,x.lo,false);put(v,38,'SSND');v.setUint32(42,8+dataBytes,false);v.setUint32(46,0,false);v.setUint32(50,0,false);let o=54;for(let i=0;i<frames;i++)for(const s0 of [buf.left[i],buf.right[i]]){const s=Math.max(-1,Math.min(1,s0));if(bits===16){v.setInt16(o,Math.round(s<0?s*32768:s*32767),false);o+=2;}else if(bits===24){const q=Math.round(s<0?s*8388608:s*8388607);v.setUint8(o,(q>>16)&255);v.setUint8(o+1,(q>>8)&255);v.setUint8(o+2,q&255);o+=3;}else{v.setInt32(o,Math.round(s<0?s*2147483648:s*2147483647),false);o+=4;}}return new Uint8Array(ab);
}

export function decodeAiff(bytes:Uint8Array):StereoBuffer{
 if(bytes.length<12||tag(bytes,0)!=='FORM'||!['AIFF','AIFC'].includes(tag(bytes,8)))throw new Error('Not an AIFF file');if(tag(bytes,8)==='AIFC')throw new Error('Compressed AIFC is not supported by the project PCM reader');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),formSize=v.getUint32(4,false),limit=Math.min(bytes.length,formSize+8);if(formSize+8>bytes.length)throw new Error('Truncated AIFF container');let p=12,ch=0,frames=0,bits=0,sr=0,ssnd=-1,ssndLen=0,offset=0,haveComm=false;
 while(p+8<=limit){const id=tag(bytes,p),len=v.getUint32(p+4,false),body=p+8,end=body+len;if(end>limit)throw new Error(`Truncated AIFF ${id} chunk`);if(id==='COMM'){if(len<18)throw new Error('Invalid AIFF COMM chunk');ch=v.getUint16(body,false);frames=v.getUint32(body+2,false);bits=v.getUint16(body+6,false);sr=Math.round(readExt80(v,body+8));haveComm=true;}else if(id==='SSND'&&ssnd<0){if(len<8)throw new Error('Invalid AIFF SSND chunk');offset=v.getUint32(body,false);if(offset>len-8)throw new Error('Invalid AIFF SSND offset');ssnd=body+8+offset;ssndLen=len-8-offset;}p=end+(len&1);}
 if(!haveComm||ssnd<0)throw new Error('AIFF requires COMM and SSND chunks');if(ch!==1&&ch!==2)throw new Error('AIFF must be mono or stereo');if(![16,24,32].includes(bits)||!Number.isFinite(sr)||sr<1||sr>768000)throw new Error('Unsupported AIFF PCM format');const bps=bits/8,available=Math.floor(ssndLen/(ch*bps)),count=Math.min(frames||available,available);if(count>MAX_AIFF_FRAMES)throw new Error('AIFF exceeds safe frame limit');const l=new Float32Array(count),r=new Float32Array(count);let o=ssnd;const read=()=>{if(bits===16){const x=v.getInt16(o,false)/32768;o+=2;return x;}if(bits===24){let q=(v.getUint8(o)<<16)|(v.getUint8(o+1)<<8)|v.getUint8(o+2);if(q&0x800000)q|=0xff000000;o+=3;return q/8388608;}const x=v.getInt32(o,false)/2147483648;o+=4;return x;};for(let i=0;i<count;i++){l[i]=read();r[i]=ch===2?read():l[i];}return {sampleRate:sr,left:l,right:r,duration:count/sr};
}
