import {Project,StereoBuffer} from '../core/types.js';
import {serializeSession} from '../core/sessionSchema.js';
import {renderProject} from '../audio/render.js';
import {encodeWav,encodeMonoWav} from './wav.js';
import {createZip} from './zip.js';
function safe(s:string){return s.replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'')||'track'}
export function stimulusManifest(project:Project){return {format:'mindaural-stimulus-manifest',version:1,generatedAt:new Date().toISOString(),project:{id:project.id,title:project.title,revision:project.revision,schemaVersion:project.schemaVersion,engineVersion:project.provenance.engineVersion,sampleRate:project.sampleRate,duration:project.duration},evidence:project.evidence,voices:project.voices.map(v=>({id:v.id,name:v.name,type:v.type,leftHz:v.leftHz,rightHz:v.rightHz,beatHz:Math.abs(v.rightHz-v.leftHz),centerHz:(v.leftHz+v.rightHz)/2,amplitude:v.amplitude,leftLevel:v.leftLevel,rightLevel:v.rightLevel,phaseLeft:v.phaseLeft,phaseRight:v.phaseRight,waveform:v.waveform,duty:v.duty,start:v.start,duration:v.duration,automation:v.automation,links:v.links,routingBus:v.routingBus})),noiseTracks:project.noiseTracks,audioTracks:project.audioTracks.map(a=>({...a,asset:project.assets.find(x=>x.id===a.assetId)})),segments:project.segments,provenance:project.provenance};}
export function recipeJson(project:Project){const s=serializeSession(project) as any;s.assets=(s.assets||[]).map((a:any)=>({...a,embeddedPath:undefined}));return JSON.stringify({format:'mindaural-recipe',version:1,session:s},null,2);}
export function researchManifestJson(project:Project){return JSON.stringify(stimulusManifest(project),null,2);}
export type ExportScope='full'|'stimulus'|'background';
export function scopeProject(project:Project,scope:ExportScope):Project{const p=structuredClone(project);if(scope==='stimulus'){p.noiseTracks=[];p.audioTracks=[];}else if(scope==='background'){p.voices=[];}return p;}
export function renderScope(project:Project,assets:Record<string,StereoBuffer>,scope:ExportScope,start=0,duration?:number){return renderProject(scopeProject(project,scope),{start,duration:duration??Math.max(0,project.duration-start),assets});}
export function createStemBundle(project:Project,assets:Record<string,StereoBuffer>){const entries:Record<string,Uint8Array|string>={'manifest.json':JSON.stringify(stimulusManifest(project),null,2)};for(const v of project.voices){const p=structuredClone(project);p.voices=p.voices.filter(x=>x.id===v.id);p.noiseTracks=[];p.audioTracks=[];entries[`stems/voice-${safe(v.name)}.wav`]=encodeWav(renderProject(p,{assets}),24);}for(const n of project.noiseTracks){const p=structuredClone(project);p.voices=[];p.noiseTracks=p.noiseTracks.filter(x=>x.id===n.id);p.audioTracks=[];entries[`stems/noise-${safe(n.name)}.wav`]=encodeWav(renderProject(p,{assets}),24);}for(const a of project.audioTracks){const p=structuredClone(project);p.voices=[];p.noiseTracks=[];p.audioTracks=p.audioTracks.filter(x=>x.id===a.id);entries[`stems/audio-${safe(a.name)}.wav`]=encodeWav(renderProject(p,{assets}),24);}return createZip(entries);}
export function createDiagnosticChannels(project:Project,assets:Record<string,StereoBuffer>){const b=renderProject(project,{assets});return {left:encodeMonoWav(b.left,b.sampleRate,24),right:encodeMonoWav(b.right,b.sampleRate,24)};}
