import {StereoBuffer} from '../core/types.js';

function crc8(bytes:Uint8Array){let crc=0;for(const b of bytes){crc^=b;for(let i=0;i<8;i++)crc=(crc&0x80)?((crc<<1)^0x07)&0xff:(crc<<1)&0xff;}return crc;}
function crc16(bytes:Uint8Array){let crc=0;for(const b of bytes){crc^=b<<8;for(let i=0;i<8;i++)crc=(crc&0x8000)?((crc<<1)^0x8005)&0xffff:(crc<<1)&0xffff;}return crc;}
function utf8Uint(n:number){n=Math.max(0,Math.floor(n));if(n<0x80)return [n];if(n<0x800)return [0xc0|(n>>6),0x80|(n&63)];if(n<0x10000)return [0xe0|(n>>12),0x80|((n>>6)&63),0x80|(n&63)];if(n<0x200000)return [0xf0|(n>>18),0x80|((n>>12)&63),0x80|((n>>6)&63),0x80|(n&63)];if(n<0x4000000)return [0xf8|(n>>24),0x80|((n>>18)&63),0x80|((n>>12)&63),0x80|((n>>6)&63),0x80|(n&63)];return [0xfc|((n/1073741824)&1),0x80|((n>>24)&63),0x80|((n>>18)&63),0x80|((n>>12)&63),0x80|((n>>6)&63),0x80|(n&63)];}
function put24(a:Uint8Array,o:number,n:number){a[o]=(n>>>16)&255;a[o+1]=(n>>>8)&255;a[o+2]=n&255;}
function pcmInt(x:number,bits:16|24){x=Math.max(-1,Math.min(1,x));return Math.round(x<0?x*Math.pow(2,bits-1):x*(Math.pow(2,bits-1)-1));}
function writeSigned(out:number[],n:number,bits:16|24){if(bits===16){out.push((n>>8)&255,n&255);}else out.push((n>>16)&255,(n>>8)&255,n&255);}

function makeFrame(buf:StereoBuffer,start:number,count:number,bits:16|24,frameNo:number){const header:number[]=[0xff,0xf8,0x70,0x10|((bits===16?4:6)<<1),...utf8Uint(frameNo),(count-1)>>8,(count-1)&255];header.push(crc8(Uint8Array.from(header)));const body:number[]=[];for(const channel of [buf.left,buf.right]){body.push(0x02);for(let i=0;i<count;i++)writeSigned(body,pcmInt(channel[start+i],bits),bits);}const frame=Uint8Array.from([...header,...body]);const c=crc16(frame);return Uint8Array.from([...frame,(c>>8)&255,c&255]);}

export function encodeFlac(buf:StereoBuffer,bits:16|24=24,blockSize=4096){if(buf.left.length!==buf.right.length)throw new Error('FLAC requires equal channel lengths');if(!Number.isInteger(buf.sampleRate)||buf.sampleRate<1||buf.sampleRate>0xfffff)throw new Error('FLAC sample rate is out of range');blockSize=Math.max(16,Math.min(65535,Math.floor(blockSize)));const frames:Uint8Array[]=[];for(let p=0,n=0;p<buf.left.length;p+=blockSize,n++)frames.push(makeFrame(buf,p,Math.min(blockSize,buf.left.length-p),bits,n));const minBlock=buf.left.length?Math.min(blockSize,buf.left.length):blockSize,maxBlock=buf.left.length?Math.min(blockSize,buf.left.length):blockSize,minFrame=frames.length?Math.min(...frames.map(x=>x.length)):0,maxFrame=frames.length?Math.max(...frames.map(x=>x.length)):0;const stream=new Uint8Array(4+4+34);stream.set([0x66,0x4c,0x61,0x43],0);stream[4]=0x80;put24(stream,5,34);const v=new DataView(stream.buffer);v.setUint16(8,minBlock,false);v.setUint16(10,maxBlock,false);put24(stream,12,minFrame);put24(stream,15,maxFrame);let packed=(BigInt(buf.sampleRate)<<44n)|(1n<<41n)|(BigInt(bits-1)<<36n)|BigInt(buf.left.length);for(let i=0;i<8;i++)stream[18+7-i]=Number((packed>>BigInt(i*8))&255n);let size=stream.length;for(const f of frames)size+=f.length;const out=new Uint8Array(size);out.set(stream);let o=stream.length;for(const f of frames){out.set(f,o);o+=f.length;}return out;}

function readUtf8Uint(a:Uint8Array,state:{o:number}){const b=a[state.o++];if(b<0x80)return b;let count=0,mask=0x80;while(b&mask){count++;mask>>=1;}if(count<2||count>6)throw new Error('Invalid FLAC UTF-8 integer');let n=b&((1<<(7-count))-1);for(let i=1;i<count;i++){const c=a[state.o++];if((c&0xc0)!==0x80)throw new Error('Invalid FLAC UTF-8 continuation');n=n*64+(c&63);}return n;}
function readSigned(a:Uint8Array,state:{o:number},bits:number){if(bits===16){let n=(a[state.o]<<8)|a[state.o+1];state.o+=2;if(n&0x8000)n-=0x10000;return n/32768;}if(bits===24){let n=(a[state.o]<<16)|(a[state.o+1]<<8)|a[state.o+2];state.o+=3;if(n&0x800000)n-=0x1000000;return n/8388608;}throw new Error('Unsupported FLAC bit depth');}
export function decodeFlacVerbatim(bytes:Uint8Array):StereoBuffer{if(bytes.length<42||String.fromCharCode(...bytes.slice(0,4))!=='fLaC')throw new Error('Not a FLAC stream');let o=4,sampleRate=0,bits=0,total=0,last=false;while(!last){if(o+4>bytes.length)throw new Error('Truncated FLAC metadata');const h=bytes[o++];last=!!(h&0x80);const type=h&0x7f,len=(bytes[o]<<16)|(bytes[o+1]<<8)|bytes[o+2];o+=3;if(o+len>bytes.length)throw new Error('Truncated FLAC metadata block');if(type===0){if(len!==34)throw new Error('Invalid STREAMINFO');let x=0n;for(let i=0;i<8;i++)x=(x<<8n)|BigInt(bytes[o+10+i]);sampleRate=Number((x>>44n)&0xfffffn);const channels=Number((x>>41n)&7n)+1;bits=Number((x>>36n)&31n)+1;total=Number(x&0xfffffffffn);if(channels!==2)throw new Error('Only stereo FLAC is supported by the deterministic decoder');if(bits!==16&&bits!==24)throw new Error('Only 16/24-bit verbatim FLAC is supported by the deterministic decoder');}o+=len;}if(!sampleRate)throw new Error('Missing FLAC STREAMINFO');const left=new Float32Array(total),right=new Float32Array(total);let written=0;while(o<bytes.length&&written<total){const frameStart=o;if(bytes[o]!==0xff||(bytes[o+1]&0xfe)!==0xf8)throw new Error('Invalid FLAC frame sync');o+=2;const blockCode=bytes[o]>>4,srCode=bytes[o]&15;o++;const assignment=bytes[o]>>4,sizeCode=(bytes[o]>>1)&7;o++;if(blockCode!==7||srCode!==0||assignment!==1||!((bits===16&&sizeCode===4)||(bits===24&&sizeCode===6)))throw new Error('FLAC frame uses features outside deterministic verbatim subset');const s={o};readUtf8Uint(bytes,s);o=s.o;const count=((bytes[o]<<8)|bytes[o+1])+1;o+=2;const headerNoCrc=bytes.slice(frameStart,o),headerCrc=bytes[o++];if(crc8(headerNoCrc)!==headerCrc)throw new Error('FLAC header CRC mismatch');for(let ch=0;ch<2;ch++){if(bytes[o++]!==0x02)throw new Error('Only FLAC verbatim subframes are supported');const st={o};const dst=ch===0?left:right;for(let i=0;i<count&&written+i<total;i++)dst[written+i]=readSigned(bytes,st,bits);o=st.o;}if(o+2>bytes.length)throw new Error('Truncated FLAC frame CRC');const expect=(bytes[o]<<8)|bytes[o+1],actual=crc16(bytes.slice(frameStart,o));o+=2;if(expect!==actual)throw new Error('FLAC frame CRC mismatch');written+=count;}if(written!==total)throw new Error(`FLAC sample count mismatch: ${written}/${total}`);return {sampleRate,left,right,duration:total/sampleRate};}
