import assert from 'node:assert/strict';
import {createDefaultProject,setCenterBeat} from '../dist/src/core/project.js';
import {History} from '../dist/src/core/history.js';
import {renderProject,renderProjectChunks} from '../dist/src/audio/render.js';
import {goertzel,stats,analyzeStereo,compareAgainstProject,cpuSpectrogram} from '../dist/src/audio/analyze.js';
import {renderLightControl,analyzeLightControl} from '../dist/src/labs/lightControl.js';
import {encodeWav,decodeWav} from '../dist/src/formats/wav.js';
import {encodeAiff,decodeAiff} from '../dist/src/formats/aiff.js';
import {encodeFlac,decodeFlacVerbatim} from '../dist/src/formats/flac.js';
import {exportProjectPackage,importProjectPackage,importProjectPackageDetailed} from '../dist/src/formats/projectPackage.js';
import {serializeSession,deserializeSession} from '../dist/src/core/sessionSchema.js';
import {createZip,readStoredZip} from '../dist/src/formats/zip.js';
import {createSigningKey,encryptSigningKey,decryptSigningKey} from '../dist/src/security/signing.js';
import {makeOpusHead,makeOpusTags,muxOggOpus,muxWebmOpus} from '../dist/src/formats/opus.js';
import {migrateSessionDocument} from '../dist/src/core/migrations.js';

const tests=[];const test=(name,fn)=>tests.push([name,fn]);
const close=(a,b,t,msg)=>assert.ok(Math.abs(a-b)<=t,`${msg||''} expected ${b}±${t}, got ${a}`);


test('history undo/redo preserves snapshots',()=>{const p=createDefaultProject('A'),h=new History(p,10),b={...p,title:'B'};h.push(b);const u=h.undo();assert.equal(u.title,'A');const r=h.redo();assert.equal(r.title,'B');});

test('binaural carriers render on separate channels',()=>{const p=createDefaultProject('signal');p.duration=2;p.sampleRate=48000;p.masterGain=1;p.voices[0]={...setCenterBeat(p.voices[0],400,10),duration:2,fadeIn:.01,fadeOut:.01,amplitude:.2};const b=renderProject(p);assert.equal(b.left.length,96000);const l395=goertzel(b.left,48000,395),l405=goertzel(b.left,48000,405),r395=goertzel(b.right,48000,395),r405=goertzel(b.right,48000,405);assert.ok(l395>l405*20,`left isolation ${l395}/${l405}`);assert.ok(r405>r395*20,`right isolation ${r405}/${r395}`);const s=stats(b);assert.equal(s.clipping,false);});

test('center/beat convenience preserves exact pair',()=>{const p=createDefaultProject();p.voices[0]=setCenterBeat(p.voices[0],400,7.83);close(p.voices[0].leftHz,396.085,1e-9);close(p.voices[0].rightHz,403.915,1e-9);});

test('beat automation changes rendered right/left relationship',()=>{const p=createDefaultProject();p.duration=2;p.voices[0].duration=2;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;p.voices[0].automation=[{parameter:'beatHz',points:[{id:'a',time:0,value:8,curve:'linear'},{id:'b',time:2,value:12,curve:'linear'}]}];const b=renderProject(p);assert.ok(Number.isFinite(b.left[100])&&Number.isFinite(b.right[100]));assert.notEqual(b.left[1000],b.right[1000]);});




test('parameter links drive beat frequency and pan automation affects channels',()=>{const p=createDefaultProject();p.duration=.5;p.masterGain=.4;p.voices[0].duration=.5;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;p.voices[0].links=[{id:'track-time',source:'time',target:'beatHz',scale:20,offset:5,min:5,max:15,quantize:1},{id:'pan-by-time',source:'time',target:'pan',scale:4,offset:-1,min:-1,max:1}];const b=renderProject(p);const earlyL=Math.abs(b.left[1000]),earlyR=Math.abs(b.right[1000]),lateL=Math.abs(b.left[22000]),lateR=Math.abs(b.right[22000]);assert.ok(Number.isFinite(earlyL+earlyR+lateL+lateR));const first=renderProject(p,{duration:.05}),last=renderProject(p,{start:.45,duration:.05});assert.ok(stats(first).rmsLeft>stats(first).rmsRight*1.5,'early pan should favor left');assert.ok(stats(last).rmsRight>stats(last).rmsLeft*1.5,'late pan should favor right');});

test('offline renderer preserves overload for scientific clipping detection',()=>{const p=createDefaultProject();p.duration=.1;p.voices[0].duration=.1;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;p.voices[0].amplitude=2;p.masterGain=1;const b=renderProject(p),s=stats(b);assert.equal(s.clipping,true);assert.ok(s.peakLeft>1||s.peakRight>1,'offline reference must not silently hard-clip');});
test('stateful chunk rendering equals full rendering',()=>{const p=createDefaultProject();p.duration=1.1;p.voices[0].duration=1.1;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;const full=renderProject(p),chunks=[...renderProjectChunks(p,.13)],joinedL=new Float32Array(full.left.length),joinedR=new Float32Array(full.right.length);let o=0;for(const c of chunks){joinedL.set(c.left,o);joinedR.set(c.right,o);o+=c.left.length;}assert.equal(o,full.left.length);for(let i=0;i<full.left.length;i+=997){close(joinedL[i],full.left[i],1e-7,'chunk left');close(joinedR[i],full.right[i],1e-7,'chunk right');}});

test('selection render preserves phase from project time zero',()=>{const p=createDefaultProject();p.duration=2;p.voices[0].duration=2;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;const full=renderProject(p);const sel=renderProject(p,{start:1,duration:.25});const start=Math.round(p.sampleRate*1);for(let i=0;i<1000;i++){close(sel.left[i],full.left[start+i],1e-6,'selection left');close(sel.right[i],full.right[start+i],1e-6,'selection right');}});

test('noise stereo correlation control changes measured correlation',()=>{const p=createDefaultProject();p.voices=[];p.duration=1;p.noiseTracks=[{id:'n',name:'Noise',kind:'white',amplitude:.1,slopeDbOct:0,stereoCorrelation:1,start:0,duration:1,loop:false,mute:false,solo:false}];const linked=stats(renderProject(p,{seed:123})).correlation;p.noiseTracks[0].stereoCorrelation=0;const independent=stats(renderProject(p,{seed:123})).correlation;assert.ok(linked>.99,`linked correlation ${linked}`);assert.ok(Math.abs(independent)<.08,`independent correlation ${independent}`);});

test('custom harmonic and band-limited waveforms render finite non-sine output',()=>{const p=createDefaultProject();p.duration=.05;p.voices[0].duration=.05;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;p.voices[0].waveform='custom-harmonic';p.voices[0].harmonics=[1,.5,.25];const a=renderProject(p);p.voices[0].waveform='bandlimited-square';const b=renderProject(p);assert.ok(a.left.every(Number.isFinite)&&b.left.every(Number.isFinite));assert.notEqual(a.left[137],b.left[137]);});
test('background interval and stereo width controls affect audio-track mix',()=>{const p=createDefaultProject();p.voices=[];p.duration=.1;const src={sampleRate:1000,left:Float32Array.from({length:100},(_,i)=>Math.sin(i*.1)),right:Float32Array.from({length:100},(_,i)=>-Math.sin(i*.1)),duration:.1};p.audioTracks=[{id:'a',name:'a',assetId:'x',start:0,duration:.1,offset:0,amplitude:.5,pan:0,stereoWidth:0,intervalSeconds:.04,intervalOnSeconds:.02,loop:false,fadeIn:0,fadeOut:0,mute:false,solo:false}];const b=renderProject(p,{sampleRate:1000,assets:{x:src}});assert.ok(Math.abs(b.left[10]-b.right[10])<1e-7,'width zero should collapse background to mid');assert.equal(b.left[30],0,'interval off window should be silent');});

test('noise automation and modulation execute in renderer',()=>{const p=createDefaultProject();p.voices=[];p.duration=.2;p.sampleRate=4000;p.masterGain=1;p.noiseTracks=[{id:'na',name:'Automated noise',kind:'white',amplitude:.02,slopeDbOct:0,stereoCorrelation:1,start:0,duration:.2,loop:false,mute:false,solo:false,automation:[{parameter:'amplitude',points:[{id:'n0',time:0,value:.01,curve:'linear'},{id:'n1',time:.2,value:.3,curve:'linear'}]}],modulation:[{target:'amplitude',rateHz:10,depth:.01}]}];const b=renderProject(p,{seed:7});const q=(a,b)=>stats({sampleRate:p.sampleRate,left:b.left.slice(a,b),right:b.right.slice(a,b),duration:(b-a)/p.sampleRate});const early=stats({sampleRate:p.sampleRate,left:b.left.slice(0,160),right:b.right.slice(0,160),duration:.04}),late=stats({sampleRate:p.sampleRate,left:b.left.slice(640,800),right:b.right.slice(640,800),duration:.04});assert.ok(late.rmsLeft>early.rmsLeft*3,`noise automation ${early.rmsLeft} -> ${late.rmsLeft}`);});

test('background automation executes gain and pan',()=>{const p=createDefaultProject();p.voices=[];p.duration=.2;p.sampleRate=1000;p.masterGain=1;const src={sampleRate:1000,left:Float32Array.from({length:200},()=>.5),right:Float32Array.from({length:200},()=>.5),duration:.2};p.audioTracks=[{id:'aa',name:'Automated background',assetId:'x',start:0,duration:.2,offset:0,amplitude:.2,pan:0,stereoWidth:1,loop:false,fadeIn:0,fadeOut:0,mute:false,solo:false,automation:[{parameter:'amplitude',points:[{id:'a0',time:0,value:.1,curve:'linear'},{id:'a1',time:.2,value:.8,curve:'linear'}]},{parameter:'pan',points:[{id:'p0',time:0,value:-1,curve:'linear'},{id:'p1',time:.2,value:1,curve:'linear'}]}]}];const b=renderProject(p,{sampleRate:1000,assets:{x:src}});assert.ok(Math.abs(b.left[10])>Math.abs(b.right[10])*3,'early pan should favor left');assert.ok(Math.abs(b.right[190])>Math.abs(b.left[190])*3,'late pan should favor right');assert.ok(Math.abs(b.right[190])>Math.abs(b.left[10])*3,'gain automation should rise');});

test('analyzer flags mono/clipping and validates clean project carriers',()=>{const p=createDefaultProject();p.duration=1;p.voices[0].duration=1;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;const b=renderProject(p),cmp=compareAgainstProject(b,p,1);assert.equal(cmp.pass,true);const mono={...b,right:b.left.slice()},a=analyzeStereo(mono);assert.equal(a.mono,true);assert.ok(a.integrityIssues.some(x=>x.includes('mono')));});
test('CPU spectrogram dimensions and timing are deterministic',()=>{const x=new Float32Array(4096);for(let i=0;i<x.length;i++)x[i]=Math.sin(2*Math.PI*440*i/48000);const s=cpuSpectrogram(x,48000,32,1024,512);assert.equal(s.bins,32);assert.equal(s.frames,7);assert.equal(s.magnitudes.length,224);assert.equal(s.backend,'cpu');});
test('legacy 19.2 kHz light-control renderer produces detectable carrier',()=>{const b=renderLightControl(.25,48000,{frequencyHz:10,leftAmplitude:.3,rightAmplitude:.15,leftPhase:0,rightPhase:Math.PI/2,duty:.5,waveform:'square'}),a=analyzeLightControl(b);assert.equal(a.present,true);assert.ok(a.leftCarrierMagnitude>a.rightCarrierMagnitude*1.6);});

test('WAV 24-bit round trip retains stereo and duration',()=>{const p=createDefaultProject();p.duration=.25;p.voices[0].duration=.25;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;const b=renderProject(p),w=encodeWav(b,24),d=decodeWav(w);assert.equal(d.sampleRate,48000);assert.equal(d.left.length,b.left.length);close(d.duration,b.duration,1e-9);close(d.left[100],b.left[100],2/8388608);close(d.right[100],b.right[100],2/8388608);});

test('WAV decoder accepts mono PCM and mirrors it to stereo',()=>{const mono=Float32Array.from([-.75,-.25,.25,.75]),w=new Uint8Array(44+mono.length*2),v=new DataView(w.buffer);for(const [o,s] of [[0,'RIFF'],[8,'WAVE'],[12,'fmt '],[36,'data']])for(let i=0;i<4;i++)v.setUint8(o+i,s.charCodeAt(i));v.setUint32(4,w.length-8,true);v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,8000,true);v.setUint32(28,16000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);v.setUint32(40,mono.length*2,true);for(let i=0;i<mono.length;i++)v.setInt16(44+i*2,Math.round(mono[i]*32768),true);const d=decodeWav(w);assert.equal(d.left.length,mono.length);for(let i=0;i<mono.length;i++){close(d.left[i],d.right[i],1e-6,'mono mirror');close(d.left[i],mono[i],1/32768,'mono decode');}});

test('AIFF 24-bit round trip retains stereo and duration',()=>{const p=createDefaultProject();p.duration=.05;p.voices[0].duration=.05;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;const b=renderProject(p),a=encodeAiff(b,24),d=decodeAiff(a);assert.equal(new TextDecoder().decode(a.slice(0,4)),'FORM');assert.equal(d.sampleRate,b.sampleRate);assert.equal(d.left.length,b.left.length);close(d.left[100],b.left[100],2/8388608);close(d.right[100],b.right[100],2/8388608);});


test('FLAC 24-bit deterministic verbatim round trip retains signal',()=>{const p=createDefaultProject();p.duration=.08;p.voices[0].duration=.08;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;const b=renderProject(p),f=encodeFlac(b,24,1024),d=decodeFlacVerbatim(f);assert.equal(new TextDecoder().decode(f.slice(0,4)),'fLaC');assert.equal(d.sampleRate,b.sampleRate);assert.equal(d.left.length,b.left.length);for(let i=0;i<b.left.length;i+=311){close(d.left[i],b.left[i],2/8388608);close(d.right[i],b.right[i],2/8388608);}});

test('canonical session serializer round trips app model',()=>{const p=createDefaultProject('Schema Test');p.voices[0].automation=[{parameter:'beatHz',points:[{id:'x',time:0,value:10,curve:'linear'},{id:'y',time:3,value:7.83,curve:'smooth'}]}];const s=serializeSession(p);assert.equal(s.schemaVersion,'1.0.0');assert.equal(s.tracks[0].type,'stimulus');assert.equal(s.tracks[0].voices[0].leftHz,p.voices[0].leftHz);const q=deserializeSession(s);assert.equal(q.title,p.title);close(q.voices[0].automation[0].points[1].time,3,1/p.sampleRate);});


test('canonical session does not invent hashes for unresolved external assets',()=>{const p=createDefaultProject();p.assets=[{id:'ext',name:'external.wav',mime:'audio/wav',size:123,license:'user-owned',source:'external'}];const s=serializeSession(p);assert.equal('sha256' in s.assets[0],false);const q=deserializeSession(s);assert.equal(q.assets[0].hash,undefined);});
test('.bbeat package round trips and reports modified entries',async()=>{const p=createDefaultProject('Package Test');const bytes=await exportProjectPackage(p);const q=await importProjectPackage(bytes);assert.equal(q.title,p.title);assert.equal(q.voices[0].leftHz,p.voices[0].leftHz);const bad=bytes.slice();const i=bad.findIndex((x,idx)=>idx>100&&x===80);if(i>0)bad[i]^=1;let caught;try{await importProjectPackage(bad);}catch(e){caught=e;}assert.ok(caught?.state==='modified'||/Modified package entry|integrity/i.test(String(caught)),'tampering must identify modified package state');});


test('.bbeat signed package verifies and distinguishes unbound/account-bound states',async()=>{const p=createDefaultProject('Signed Package'),key=await createSigningKey(),box=await encryptSigningKey(key,'correct horse battery staple'),unlocked=await decryptSigningKey(box,'correct horse battery staple');assert.equal(unlocked.publicKey,key.publicKey);assert.equal(unlocked.privateKey,key.privateKey);await assert.rejects(()=>decryptSigningKey(box,'wrong-passphrase'));const bytes=await exportProjectPackage(p,{},key),result=await importProjectPackageDetailed(bytes);assert.equal(result.signature.state,'valid-unbound');const boundKey={...key,accountId:'acct-test'},bound=await importProjectPackageDetailed(await exportProjectPackage(p,{},boundKey),{[key.publicKey]:'acct-test'});assert.equal(bound.signature.state,'valid-account-bound');});
test('ZIP reader rejects path traversal',()=>{assert.throws(()=>createZip({'../evil.txt':'x'}));const z=createZip({'safe.txt':'ok'});assert.equal(new TextDecoder().decode(readStoredZip(z)['safe.txt']),'ok');});


test('segment repetition remaps automation and track scoping',()=>{const p=createDefaultProject();p.duration=.1;p.sampleRate=10000;p.masterGain=.5;p.voices[0].duration=.05;p.voices[0].fadeIn=0;p.voices[0].fadeOut=0;p.voices[0].automation=[{parameter:'amplitude',points:[{id:'a',time:0,value:0,curve:'linear'},{id:'b',time:.05,value:.5,curve:'linear'}]}];p.segments=[{id:'s',name:'repeat',start:0,duration:.05,repeat:2,crossfade:0,phaseContinuous:true}];const b=renderProject(p),first=stats({sampleRate:p.sampleRate,left:b.left.slice(350,450),right:b.right.slice(350,450),duration:.01}),restart=stats({sampleRate:p.sampleRate,left:b.left.slice(510,610),right:b.right.slice(510,610),duration:.01});assert.ok(first.rmsLeft>restart.rmsLeft*2,'automation should restart with repeated segment local time');p.segments[0].trackIds=['different'];const ungated=renderProject(p);assert.ok(stats(ungated).rmsLeft>0,'segment scoped to another track must not gate this voice');});

test('session schema preserves segment scope and overrides',()=>{const p=createDefaultProject();p.segments[0].trackIds=[p.voices[0].id];p.segments[0].overrides={beatHz:7.83,amplitude:.1};p.segments[0].phaseContinuous=true;const q=deserializeSession(serializeSession(p));assert.deepEqual(q.segments[0].trackIds,p.segments[0].trackIds);close(q.segments[0].overrides.beatHz,7.83,1e-9);});

test('Ogg Opus muxer writes valid capture pages and terminal EOS',()=>{const packets=[{data:Uint8Array.of(1,2,3,4),samples:960,timestampUs:0},{data:Uint8Array.of(5,6,7),samples:960,timestampUs:20000}],o=muxOggOpus(packets,2,48000);const text=new TextDecoder('latin1').decode(o);assert.ok(text.startsWith('OggS'));assert.ok(text.includes('OpusHead'));assert.ok(text.includes('OpusTags'));let pages=0,lastFlags=0,p=0;while(p+27<=o.length){assert.equal(String.fromCharCode(...o.slice(p,p+4)),'OggS');const segs=o[p+26];let payload=0;for(let i=0;i<segs;i++)payload+=o[p+27+i];lastFlags=o[p+5];pages++;p+=27+segs+payload;}assert.equal(p,o.length);assert.equal(pages,4);assert.ok(lastFlags&4,'last Ogg page must be EOS');});

test('WebM Opus muxer contains EBML, WebM and Opus track metadata',()=>{const packets=[{data:Uint8Array.of(0xf8,0xff,0xfe),samples:960,timestampUs:0},{data:Uint8Array.of(0xf8,0xaa),samples:960,timestampUs:20000}],w=muxWebmOpus(packets,2,48000),text=new TextDecoder('latin1').decode(w);assert.deepEqual(Array.from(w.slice(0,4)),[0x1a,0x45,0xdf,0xa3]);assert.ok(text.includes('webm'));assert.ok(text.includes('A_OPUS'));assert.ok(text.includes('OpusHead'));});

let failed=0;for(const [name,fn] of tests){try{await fn();console.log(`PASS ${name}`);}catch(e){failed++;console.error(`FAIL ${name}`);console.error(e);}}console.log(`Runtime tests: ${tests.length-failed}/${tests.length} passed`);process.exit(failed?1:0);
