import {Project} from '../core/types.js';
const DB='mindaural',STORE='playlists',VERSION=3;
export interface PlaylistItem{id:string;title:string;project:Project;}
export interface Playlist{id:string;title:string;items:PlaylistItem[];createdAt:string;updatedAt:string;}
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('projects'))r.result.createObjectStore('projects',{keyPath:'id'});if(!r.result.objectStoreNames.contains('assets'))r.result.createObjectStore('assets',{keyPath:'id'});if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export function createPlaylist(title='New playlist'):Playlist{const now=new Date().toISOString();return {id:crypto.randomUUID(),title,items:[],createdAt:now,updatedAt:now};}
export async function savePlaylist(p:Playlist){const db=await open(),row={...structuredClone(p),updatedAt:new Date().toISOString()};await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();return row;}
export async function loadPlaylists():Promise<Playlist[]>{const db=await open(),rows=await new Promise<Playlist[]>((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return rows.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
export async function deletePlaylist(id:string){const db=await open();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();}
export async function addProjectToPlaylist(playlist:Playlist,project:Project){const item={id:crypto.randomUUID(),title:project.title,project:structuredClone(project)};return savePlaylist({...playlist,items:[...playlist.items,item]});}
