import {SpectrumResult} from '../core/types.js';
import {cpuSpectrum,cpuSpectrogram,SpectrogramResult} from '../audio/analyze.js';
export interface GpuStatus{available:boolean;active:boolean;reason?:string;adapterName?:string;limits?:Record<string,number>;}
export class WebGpuAnalyzer{
 private device:any=null;private status:GpuStatus={available:false,active:false,reason:'Not initialized'};
 getStatus(){return {...this.status};}
 async init(force=false){if(this.device&&!force)return this.status;try{const gpu=(navigator as any).gpu;if(!gpu){this.status={available:false,active:false,reason:'WebGPU unavailable'};return this.status;}const adapter=await gpu.requestAdapter();if(!adapter){this.status={available:false,active:false,reason:'No WebGPU adapter'};return this.status;}this.device=await adapter.requestDevice();this.device.lost.then((info:any)=>{this.device=null;this.status={available:true,active:false,reason:`Device lost: ${info?.message||'unknown'}`};});const limits:any={};for(const k of ['maxBufferSize','maxStorageBufferBindingSize','maxComputeWorkgroupSizeX','maxComputeInvocationsPerWorkgroup'])if(adapter.limits?.[k]!=null)limits[k]=Number(adapter.limits[k]);this.status={available:true,active:true,adapterName:adapter.info?.description||adapter.info?.vendor||'WebGPU adapter',limits};return this.status;}catch(e){this.device=null;this.status={available:false,active:false,reason:e instanceof Error?e.message:String(e)};return this.status;}}
 async spectrum(samples:Float32Array,sampleRate:number,bins=512):Promise<SpectrumResult>{if(!this.device)await this.init();if(!this.device)return cpuSpectrum(samples,sampleRate,bins);const n=Math.min(samples.length,4096),src=samples.slice(0,n),device=this.device;const shader=`struct P{n:u32;bins:u32;sampleRate:f32;pad:f32};@group(0) @binding(0)var<storage,read>x:array<f32>;@group(0) @binding(1)var<storage,read_write>out:array<f32>;@group(0) @binding(2)var<uniform>p:P;@compute @workgroup_size(64) fn main(@builtin(global_invocation_id)id:vec3<u32>){let k=id.x;if(k>=p.bins){return;}let f=f32(k+1u)*(p.sampleRate*.5)/f32(p.bins+1u);var re:f32=0.0;var im:f32=0.0;for(var i:u32=0u;i<p.n;i=i+1u){let a=6.28318530718*f*f32(i)/p.sampleRate;re=re+x[i]*cos(a);im=im-x[i]*sin(a);}out[k]=sqrt(re*re+im*im)/f32(p.n);}`;try{const module=device.createShaderModule({code:shader});const info=await module.getCompilationInfo?.();if(info?.messages?.some((m:any)=>m.type==='error'))throw new Error(info.messages.map((m:any)=>m.message).join('; '));const inBuf=device.createBuffer({size:Math.max(4,src.byteLength),usage:0x80|0x08,mappedAtCreation:true});new Float32Array(inBuf.getMappedRange()).set(src);inBuf.unmap();const outBuf=device.createBuffer({size:bins*4,usage:0x80|0x04}),readBuf=device.createBuffer({size:bins*4,usage:0x01|0x08}),uniform=device.createBuffer({size:16,usage:0x40|0x08,mappedAtCreation:true});const dv=new DataView(uniform.getMappedRange());dv.setUint32(0,n,true);dv.setUint32(4,bins,true);dv.setFloat32(8,sampleRate,true);uniform.unmap();const layout=device.createBindGroupLayout({entries:[{binding:0,visibility:4,buffer:{type:'read-only-storage'}},{binding:1,visibility:4,buffer:{type:'storage'}},{binding:2,visibility:4,buffer:{type:'uniform'}}]}),pipeline=device.createComputePipeline({layout:device.createPipelineLayout({bindGroupLayouts:[layout]}),compute:{module,entryPoint:'main'}}),bind=device.createBindGroup({layout,entries:[{binding:0,resource:{buffer:inBuf}},{binding:1,resource:{buffer:outBuf}},{binding:2,resource:{buffer:uniform}}]}),enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(Math.ceil(bins/64));pass.end();enc.copyBufferToBuffer(outBuf,0,readBuf,0,bins*4);device.queue.submit([enc.finish()]);await readBuf.mapAsync(1);const mags=new Float32Array(readBuf.getMappedRange().slice(0));readBuf.unmap();const freqs=new Float32Array(bins);for(let i=0;i<bins;i++)freqs[i]=(i+1)*(sampleRate*.5)/(bins+1);inBuf.destroy();outBuf.destroy();readBuf.destroy();uniform.destroy();return {frequencies:freqs,magnitudes:mags,backend:'webgpu'};}catch(e){this.status={available:true,active:false,reason:`WebGPU analysis failed: ${e instanceof Error?e.message:String(e)}; CPU fallback active`};return cpuSpectrum(samples,sampleRate,bins);}}
 async spectrogram(samples:Float32Array,sampleRate:number,bins=96,windowSize=2048,hop=512):Promise<SpectrogramResult>{if(!this.device)await this.init();if(!this.device)return cpuSpectrogram(samples,sampleRate,bins,windowSize,hop);const frames=Math.max(1,1+Math.floor(Math.max(0,samples.length-windowSize)/hop)),times=new Float32Array(frames),freqs=new Float32Array(bins),mags=new Float32Array(frames*bins);for(let f=0;f<frames;f++){const start=Math.min(f*hop,Math.max(0,samples.length-windowSize)),r=await this.spectrum(samples.subarray(start,start+windowSize),sampleRate,bins);times[f]=(start+windowSize/2)/sampleRate;if(r.backend!=='webgpu')return cpuSpectrogram(samples,sampleRate,bins,windowSize,hop);if(f===0)freqs.set(r.frequencies);mags.set(r.magnitudes,f*bins);}return {times,frequencies:freqs,magnitudes:mags,frames,bins,backend:'webgpu'};}
 async recover(){this.device=null;return this.init(true);}
}
